stages:
  - release
  - build

semantic-release:
  stage: release
  image: node:24-slim
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "dev"
  before_script:
    - apt-get update && apt-get install -y git
    - npm install @semantic-release/changelog @semantic-release/git @semantic-release/gitlab @semantic-release/exec @semantic-release/npm @semantic-release/commit-analyzer @semantic-release/release-notes-generator -D
  script:
    - touch build.env
    - npx semantic-release
  artifacts:
    reports:
      dotenv: build.env
    paths:
      - package.json

docker-build:
  image: docker:cli
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  needs:
    - job: semantic-release
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "dev"
  before_script:
    - echo "Version $NEW_VERSION"
    - if [ -z "$NEW_VERSION" ]; then echo "No new version to build."; exit 0; fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull --provenance=false -t "$CI_REGISTRY_IMAGE:$NEW_VERSION" .
    - docker push "$CI_REGISTRY_IMAGE:$NEW_VERSION"
    - |
      if [[ "$NEW_VERSION" != *"-dev"* ]]; then
        docker tag $CI_REGISTRY_IMAGE:$NEW_VERSION $CI_REGISTRY_IMAGE:latest
        docker push $CI_REGISTRY_IMAGE:latest
      else
        docker tag $CI_REGISTRY_IMAGE:$NEW_VERSION $CI_REGISTRY_IMAGE:dev
        docker push $CI_REGISTRY_IMAGE:dev
      fi
  after_script:
    - docker logout
