// This file is auto-generated by @hey-api/openapi-ts

export const AdminPointRequestSchema = {
    properties: {
        user_ids: {
            items: {
                type: 'integer'
            },
            type: 'array',
            title: 'User Ids',
            description: '포인트를 지급/차감할 대상 유저 ID 목록'
        },
        amount: {
            type: 'integer',
            title: 'Amount',
            description: '변동될 포인트 (양수는 지급, 음수는 차감)'
        },
        reason: {
            type: 'string',
            title: 'Reason',
            description: '포인트 변동 사유'
        }
    },
    type: 'object',
    required: [
        'user_ids',
        'amount',
        'reason'
    ],
    title: 'AdminPointRequest'
} as const;

export const AdminUserCreateRequestSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name',
            description: '사용자 이름'
        },
        user_type: {
            $ref: '#/components/schemas/UserType',
            description: '사용자 유형 (student, teacher, service)'
        },
        grade: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade',
            description: '학년 (학생인 경우 필수)'
        },
        number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Number',
            description: '반 (학생인 경우 필수)'
        },
        student_no: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Student No',
            description: '번호 (학생인 경우 필수)'
        }
    },
    type: 'object',
    required: [
        'name',
        'user_type'
    ],
    title: 'AdminUserCreateRequest'
} as const;

export const AdminUserUpdateRequestSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name',
            description: '사용자 이름'
        },
        permissions: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Permissions',
            description: '사용자 권한'
        }
    },
    type: 'object',
    title: 'AdminUserUpdateRequest'
} as const;

export const ChangePasswordFormSchema = {
    properties: {
        old_password: {
            type: 'string',
            title: 'Old Password'
        },
        new_password: {
            type: 'string',
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'old_password',
        'new_password'
    ],
    title: 'ChangePasswordForm'
} as const;

export const ChangePasswordNewFormSchema = {
    properties: {
        user: {
            type: 'integer',
            title: 'User'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'user',
        'password'
    ],
    title: 'ChangePasswordNewForm'
} as const;

export const ErrorResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        message: {
            type: 'string',
            title: 'Message',
            description: '에러 메시지'
        }
    },
    type: 'object',
    required: [
        'success',
        'message'
    ],
    title: 'ErrorResponse'
} as const;

export const GetLimitResponseSchema = {
    properties: {
        limit: {
            type: 'integer',
            title: 'Limit'
        },
        target_limit: {
            type: 'integer',
            title: 'Target Limit'
        }
    },
    type: 'object',
    required: [
        'limit',
        'target_limit'
    ],
    title: 'GetLimitResponse'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LoginFormSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'id',
        'password'
    ],
    title: 'LoginForm'
} as const;

export const PointHistorySchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        changed_amount: {
            type: 'integer',
            title: 'Changed Amount',
            description: '변경된 포인트의 정도'
        },
        reason: {
            type: 'string',
            title: 'Reason',
            description: '누구의 무엇의 의해서 포인트가 변경되었는지 이유'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo',
            description: '포인트가 어떠한 사유로 변경되었는지 이유'
        },
        type: {
            anyOf: [
                {
                    $ref: '#/components/schemas/PointHistoryType'
                },
                {
                    type: 'null'
                }
            ],
            description: '기록 종류'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'user_id',
        'changed_amount',
        'reason'
    ],
    title: 'PointHistory'
} as const;

export const PointHistoryTypeSchema = {
    type: 'string',
    enum: [
        'teacher',
        'cafe',
        'food',
        'etc',
        'grant',
        'quest',
        'stamp',
        'stamp_bonus'
    ],
    title: 'PointHistoryType'
} as const;

export const PointOperationSchema = {
    properties: {
        target_user_id: {
            type: 'integer',
            title: 'Target User Id'
        },
        amount: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Amount',
            description: '처리할 포인트'
        },
        change_type: {
            anyOf: [
                {
                    $ref: '#/components/schemas/PointHistoryType'
                },
                {
                    type: 'null'
                }
            ],
            description: '포인트를 처리하는 이유의 종류'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo',
            description: '포인트를 처리하는 이유'
        }
    },
    type: 'object',
    required: [
        'target_user_id',
        'amount'
    ],
    title: 'PointOperation'
} as const;

export const PostCreateRequestSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            description: '게시글 제목'
        },
        content_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Content Data',
            description: '게시글의 본문 데이터'
        }
    },
    type: 'object',
    required: [
        'title',
        'content_data'
    ],
    title: 'PostCreateRequest'
} as const;

export const PostUpdateRequestSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title',
            description: '수정할 게시글 제목'
        },
        content_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content Data',
            description: '수정할 게시글의 본문 데이터'
        }
    },
    type: 'object',
    title: 'PostUpdateRequest'
} as const;

export const PostsSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id',
            description: '게시글 고유 ID'
        },
        title: {
            type: 'string',
            title: 'Title',
            description: '게시글 제목'
        },
        views: {
            type: 'integer',
            title: 'Views',
            description: '게시글 조회수',
            default: 0
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: '게시글이 작성된 시간'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At',
            description: '게시글이 수정된 마지막 시간'
        },
        author_id: {
            type: 'integer',
            title: 'Author Id',
            description: '게시글 작성자의 고유 ID'
        }
    },
    type: 'object',
    required: [
        'title',
        'author_id'
    ],
    title: 'Posts'
} as const;

export const QuestCompleteRequestSchema = {
    properties: {
        target_user_id: {
            type: 'integer',
            title: 'Target User Id',
            description: '완료 처리할 학생의 ID'
        }
    },
    type: 'object',
    required: [
        'target_user_id'
    ],
    title: 'QuestCompleteRequest'
} as const;

export const QuestOperationSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title',
            description: '퀘스트 제목'
        },
        description: {
            type: 'string',
            title: 'Description',
            description: '퀘스트 내용'
        },
        reward: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Reward',
            description: '퀘스트 보상(포인트)'
        },
        end_date: {
            type: 'string',
            format: 'date-time',
            title: 'End Date',
            description: '퀘스트 종료 날짜'
        },
        max_repeat: {
            type: 'integer',
            minimum: 1,
            title: 'Max Repeat',
            description: '퀘스트 반복 가능 횟수',
            default: 1
        }
    },
    type: 'object',
    required: [
        'title',
        'description',
        'reward',
        'end_date'
    ],
    title: 'QuestOperation'
} as const;

export const QuestUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title',
            description: '퀘스트 제목'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description',
            description: '퀘스트 내용'
        },
        reward: {
            anyOf: [
                {
                    type: 'integer',
                    exclusiveMinimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reward',
            description: '퀘스트 보상(포인트)'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date',
            description: '퀘스트 종료 날짜'
        },
        max_repeat: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Repeat',
            description: '퀘스트 반복 가능 횟수'
        }
    },
    type: 'object',
    title: 'QuestUpdate'
} as const;

export const QuestsSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id',
            description: '퀘스트 고유 ID'
        },
        title: {
            type: 'string',
            title: 'Title',
            description: '퀘스트 제목'
        },
        description: {
            type: 'string',
            title: 'Description',
            description: '퀘스트 내용'
        },
        reward: {
            type: 'integer',
            title: 'Reward',
            description: '퀘스트 보상 포인트'
        },
        end_date: {
            type: 'string',
            format: 'date-time',
            title: 'End Date',
            description: '퀘스트 종료 날짜'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: '퀘스트를 작성한 시간'
        },
        author_id: {
            type: 'integer',
            title: 'Author Id',
            description: '퀘스트 생성 유저의 고유 ID'
        }
    },
    type: 'object',
    required: [
        'title',
        'description',
        'reward',
        'end_date',
        'author_id'
    ],
    title: 'Quests'
} as const;

export const RankingResponseSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id',
            description: '고유 ID. 교사, 서비스의 경우 자동생성. 학생의 경우 학번 사용'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: '이름'
        },
        grade: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade',
            description: '학년'
        },
        number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Number',
            description: '반'
        },
        total_point: {
            type: 'integer',
            title: 'Total Point',
            description: '누적 포인트'
        },
        rank: {
            type: 'integer',
            title: 'Rank',
            description: '현재 순위'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'grade',
        'number',
        'total_point',
        'rank'
    ],
    title: 'RankingResponse'
} as const;

export const ResponseModel_GetLimitResponse_Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            $ref: '#/components/schemas/GetLimitResponse',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[GetLimitResponse]'
} as const;

export const ResponseModel_PointHistory_Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            $ref: '#/components/schemas/PointHistory',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[PointHistory]'
} as const;

export const ResponseModel_Posts_Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            $ref: '#/components/schemas/Posts',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[Posts]'
} as const;

export const ResponseModel_Quests_Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            $ref: '#/components/schemas/Quests',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[Quests]'
} as const;

export const ResponseModel_User_Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            $ref: '#/components/schemas/User',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[User]'
} as const;

export const ResponseModel_bool_Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            type: 'boolean',
            title: 'Data',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[bool]'
} as const;

export const ResponseModel_int_Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            type: 'integer',
            title: 'Data',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[int]'
} as const;

export const ResponseModel_list_PointHistory__Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            items: {
                $ref: '#/components/schemas/PointHistory'
            },
            type: 'array',
            title: 'Data',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[list[PointHistory]]'
} as const;

export const ResponseModel_list_Posts__Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            items: {
                $ref: '#/components/schemas/Posts'
            },
            type: 'array',
            title: 'Data',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[list[Posts]]'
} as const;

export const ResponseModel_list_Quests__Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            items: {
                $ref: '#/components/schemas/Quests'
            },
            type: 'array',
            title: 'Data',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[list[Quests]]'
} as const;

export const ResponseModel_list_RankingResponse__Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            items: {
                $ref: '#/components/schemas/RankingResponse'
            },
            type: 'array',
            title: 'Data',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[list[RankingResponse]]'
} as const;

export const ResponseModel_list_StampsList__Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            items: {
                $ref: '#/components/schemas/StampsList'
            },
            type: 'array',
            title: 'Data',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[list[StampsList]]'
} as const;

export const ResponseModel_list_User__Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            items: {
                $ref: '#/components/schemas/User'
            },
            type: 'array',
            title: 'Data',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[list[User]]'
} as const;

export const ResponseModel_list_Users__Schema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        data: {
            items: {
                $ref: '#/components/schemas/Users'
            },
            type: 'array',
            title: 'Data',
            description: '응답 데이터'
        }
    },
    type: 'object',
    required: [
        'success',
        'data'
    ],
    title: 'ResponseModel[list[Users]]'
} as const;

export const StampCreateSchema = {
    properties: {
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        stamp_type: {
            $ref: '#/components/schemas/StampType'
        }
    },
    type: 'object',
    required: [
        'user_id',
        'stamp_type'
    ],
    title: 'StampCreate'
} as const;

export const StampTypeSchema = {
    type: 'string',
    enum: [
        '쓰레기 투호',
        '철권 한판',
        '큐피트의 다트',
        '제기찰겨? 날찰겨?',
        '팔씨름 최강자전',
        '부적꾸미기',
        '누르기 챌린지',
        '공놀이 괴물',
        '철면피 노래방',
        '절대음감',
        '런닝맨',
        '의자뺏기',
        '단체줄넘기',
        '수학 키캡'
    ],
    title: 'StampType',
    description: '스탬프 종류 Enum\n- 부스 이름은 추후 수정될 수 있습니다.'
} as const;

export const StampsListSchema = {
    properties: {
        stamp: {
            type: 'string',
            title: 'Stamp'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        have: {
            type: 'boolean',
            title: 'Have'
        },
        time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time'
        }
    },
    type: 'object',
    required: [
        'stamp',
        'name',
        'have',
        'time'
    ],
    title: 'StampsList'
} as const;

export const UserSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id',
            description: '고유 ID. 교사, 서비스의 경우 자동생성. 학생의 경우 학번 사용'
        },
        type: {
            $ref: '#/components/schemas/UserType',
            description: '유저 종류 (학생, 교사, 서비스)'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: '이름'
        },
        grade: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade',
            description: '학년'
        },
        number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Number',
            description: '반'
        },
        point: {
            type: 'integer',
            title: 'Point',
            description: '보유 포인트',
            default: 0
        },
        total_point: {
            type: 'integer',
            title: 'Total Point',
            description: '누적 포인트',
            default: 0
        },
        permissions: {
            type: 'integer',
            title: 'Permissions',
            description: '관리자 여부',
            default: 0
        },
        history_type: {
            anyOf: [
                {
                    $ref: '#/components/schemas/PointHistoryType'
                },
                {
                    type: 'null'
                }
            ],
            description: '해당 유저가 포인트 지급/차감시 포인트 기록 타입'
        }
    },
    type: 'object',
    required: [
        'type',
        'name',
        'grade',
        'number'
    ],
    title: 'User'
} as const;

export const UserPermissionSchema = {
    type: 'integer',
    enum: [
        0,
        131072,
        1,
        131073,
        2,
        131074,
        4,
        8,
        16,
        32,
        131104,
        64,
        128,
        256,
        512,
        1024,
        2048,
        133120,
        4096,
        8192,
        139264,
        16384,
        32768,
        65536,
        119232,
        182730,
        140816
    ],
    title: 'UserPermission',
    description: '유저 권한 IntFlag.\n작명시 `동사_목적`으로 작성하며, 대문자로만 작성한다.\n예) 포인트 관리 -> MANAGE_POINT',
    'x-enum-varnames': [
        'NONE',
        'SEARCH_USER',
        '_DEDUCT_POINT',
        'DEDUCT_POINT',
        '_GRANT_POINT',
        'GRANT_POINT',
        'NO_LIMIT_POINT',
        'CREATE_QUEST',
        'MANAGE_QUEST',
        '_GIVE_STAMP',
        'GIVE_STAMP',
        'VIEW_RANK',
        'VIEW_POINT',
        'VIEW_POINT_HISTORY',
        'MANAGE_POST',
        'CREATE_POST',
        '_VIEW_USER_POINT',
        'VIEW_USER_POINT',
        'JOIN_QUEST',
        '_MANAGE_USER',
        'MANAGE_USER',
        'VIEW_POST',
        'VIEW_STAMP',
        'VIEW_QUEST',
        'STUDENT',
        'TEACHER',
        'ADMIN'
    ],
    'x-enumNames': [
        'NONE',
        'SEARCH_USER',
        '_DEDUCT_POINT',
        'DEDUCT_POINT',
        '_GRANT_POINT',
        'GRANT_POINT',
        'NO_LIMIT_POINT',
        'CREATE_QUEST',
        'MANAGE_QUEST',
        '_GIVE_STAMP',
        'GIVE_STAMP',
        'VIEW_RANK',
        'VIEW_POINT',
        'VIEW_POINT_HISTORY',
        'MANAGE_POST',
        'CREATE_POST',
        '_VIEW_USER_POINT',
        'VIEW_USER_POINT',
        'JOIN_QUEST',
        '_MANAGE_USER',
        'MANAGE_USER',
        'VIEW_POST',
        'VIEW_STAMP',
        'VIEW_QUEST',
        'STUDENT',
        'TEACHER',
        'ADMIN'
    ]
} as const;

export const UserTypeSchema = {
    type: 'string',
    enum: [
        'student',
        'teacher',
        'service'
    ],
    title: 'UserType'
} as const;

export const UsersSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id',
            description: '고유 ID. 교사, 서비스의 경우 자동생성. 학생의 경우 학번 사용'
        },
        type: {
            $ref: '#/components/schemas/UserType',
            description: '유저 종류 (학생, 교사, 서비스)'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: '이름'
        },
        grade: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade',
            description: '학년'
        },
        number: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Number',
            description: '반'
        },
        point: {
            type: 'integer',
            title: 'Point',
            description: '보유 포인트',
            default: 0
        },
        total_point: {
            type: 'integer',
            title: 'Total Point',
            description: '누적 포인트',
            default: 0
        },
        permissions: {
            type: 'integer',
            title: 'Permissions',
            description: '관리자 여부',
            default: 0
        },
        history_type: {
            anyOf: [
                {
                    $ref: '#/components/schemas/PointHistoryType'
                },
                {
                    type: 'null'
                }
            ],
            description: '해당 유저가 포인트 지급/차감시 포인트 기록 타입'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password',
            description: '비밀번호'
        }
    },
    type: 'object',
    required: [
        'type',
        'name',
        'grade',
        'number',
        'password'
    ],
    title: 'Users'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
