// This file is auto-generated by @hey-api/openapi-ts

import type { CreatePostPostsPostResponse, CreateQuestQuestCreatePostResponse, GetHistoryListPointHistoryGetResponse, GetHistoryPointHistoryTargetIdGetResponse, GetPostPostsPostIdGetResponse, GetPostsPostsGetResponse, GetQuestQuestQuestIdGetResponse, GetUserStampsStampGetResponse, ListQuestsQuestGetResponse, UpdatePostPostsPostIdPatchResponse, UpdateQuestQuestQuestIdPutResponse } from './types.gen';

const pointHistorySchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    return data;
};

const responseModelListPointHistorySchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => pointHistorySchemaResponseTransformer(item));
    return data;
};

export const getHistoryListPointHistoryGetResponseTransformer = async (data: any): Promise<GetHistoryListPointHistoryGetResponse> => {
    data = responseModelListPointHistorySchemaResponseTransformer(data);
    return data;
};

const responseModelPointHistorySchemaResponseTransformer = (data: any) => {
    data.data = pointHistorySchemaResponseTransformer(data.data);
    return data;
};

export const getHistoryPointHistoryTargetIdGetResponseTransformer = async (data: any): Promise<GetHistoryPointHistoryTargetIdGetResponse> => {
    data = responseModelPointHistorySchemaResponseTransformer(data);
    return data;
};

const questsSchemaResponseTransformer = (data: any) => {
    data.end_date = new Date(data.end_date);
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    return data;
};

const responseModelQuestsSchemaResponseTransformer = (data: any) => {
    data.data = questsSchemaResponseTransformer(data.data);
    return data;
};

export const createQuestQuestCreatePostResponseTransformer = async (data: any): Promise<CreateQuestQuestCreatePostResponse> => {
    data = responseModelQuestsSchemaResponseTransformer(data);
    return data;
};

const responseModelListQuestsSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => questsSchemaResponseTransformer(item));
    return data;
};

export const listQuestsQuestGetResponseTransformer = async (data: any): Promise<ListQuestsQuestGetResponse> => {
    data = responseModelListQuestsSchemaResponseTransformer(data);
    return data;
};

export const getQuestQuestQuestIdGetResponseTransformer = async (data: any): Promise<GetQuestQuestQuestIdGetResponse> => {
    data = responseModelQuestsSchemaResponseTransformer(data);
    return data;
};

export const updateQuestQuestQuestIdPutResponseTransformer = async (data: any): Promise<UpdateQuestQuestQuestIdPutResponse> => {
    data = responseModelQuestsSchemaResponseTransformer(data);
    return data;
};

const postsSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    return data;
};

const responseModelListPostsSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => postsSchemaResponseTransformer(item));
    return data;
};

export const getPostsPostsGetResponseTransformer = async (data: any): Promise<GetPostsPostsGetResponse> => {
    data = responseModelListPostsSchemaResponseTransformer(data);
    return data;
};

const responseModelPostsSchemaResponseTransformer = (data: any) => {
    data.data = postsSchemaResponseTransformer(data.data);
    return data;
};

export const createPostPostsPostResponseTransformer = async (data: any): Promise<CreatePostPostsPostResponse> => {
    data = responseModelPostsSchemaResponseTransformer(data);
    return data;
};

export const getPostPostsPostIdGetResponseTransformer = async (data: any): Promise<GetPostPostsPostIdGetResponse> => {
    data = responseModelPostsSchemaResponseTransformer(data);
    return data;
};

export const updatePostPostsPostIdPatchResponseTransformer = async (data: any): Promise<UpdatePostPostsPostIdPatchResponse> => {
    data = responseModelPostsSchemaResponseTransformer(data);
    return data;
};

const stampsListSchemaResponseTransformer = (data: any) => {
    if (data.time) {
        data.time = new Date(data.time);
    }
    return data;
};

const responseModelListStampsListSchemaResponseTransformer = (data: any) => {
    data.data = data.data.map((item: any) => stampsListSchemaResponseTransformer(item));
    return data;
};

export const getUserStampsStampGetResponseTransformer = async (data: any): Promise<GetUserStampsStampGetResponse> => {
    data = responseModelListStampsListSchemaResponseTransformer(data);
    return data;
};
