// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdminPointRequest
 */
export type AdminPointRequest = {
    /**
     * User Ids
     *
     * 포인트를 지급/차감할 대상 유저 ID 목록
     */
    user_ids: Array<number>;
    /**
     * Amount
     *
     * 변동될 포인트 (양수는 지급, 음수는 차감)
     */
    amount: number;
    /**
     * Reason
     *
     * 포인트 변동 사유
     */
    reason: string;
};

/**
 * AdminUserCreateRequest
 */
export type AdminUserCreateRequest = {
    /**
     * Name
     *
     * 사용자 이름
     */
    name: string;
    /**
     * 사용자 유형 (student, teacher, service)
     */
    user_type: UserType;
    /**
     * Grade
     *
     * 학년 (학생인 경우 필수)
     */
    grade?: number | null;
    /**
     * Number
     *
     * 반 (학생인 경우 필수)
     */
    number?: number | null;
    /**
     * Student No
     *
     * 번호 (학생인 경우 필수)
     */
    student_no?: number | null;
};

/**
 * AdminUserUpdateRequest
 */
export type AdminUserUpdateRequest = {
    /**
     * Name
     *
     * 사용자 이름
     */
    name?: string | null;
    /**
     * Permissions
     *
     * 사용자 권한
     */
    permissions?: number | null;
};

/**
 * ChangePasswordForm
 */
export type ChangePasswordForm = {
    /**
     * Old Password
     */
    old_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ChangePasswordNewForm
 */
export type ChangePasswordNewForm = {
    /**
     * User
     */
    user: number;
    /**
     * Password
     */
    password: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     *
     * 에러 메시지
     */
    message: string;
};

/**
 * GetLimitResponse
 */
export type GetLimitResponse = {
    /**
     * Limit
     */
    limit: number;
    /**
     * Target Limit
     */
    target_limit: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * KaraokeBidCreate
 */
export type KaraokeBidCreate = {
    /**
     * Amount
     *
     * 입찰 금액
     */
    amount: number;
};

/**
 * KaraokeBids
 */
export type KaraokeBids = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Auction Id
     *
     * 연결된 경매의 고유 ID
     */
    auction_id: number;
    /**
     * Bidder Id
     *
     * 입찰한 유저의 고유ID
     */
    bidder_id: number;
    /**
     * Party Id
     *
     * 입찰한 유저의 파티 고유 ID
     */
    party_id: number | null;
    /**
     * Amount
     *
     * 입찰 금액
     */
    amount: number;
    /**
     * Created At
     *
     * 입찰된 시간
     */
    created_at?: Date;
};

/**
 * KaraokeCreate
 */
export type KaraokeCreate = {
    /**
     * Date
     *
     * 일자
     */
    date: Date;
    /**
     * Time
     *
     * 시간 (1~7교시, 점심시간 8)
     */
    time: number;
    /**
     * Start Time
     *
     * 경매 시작 시간
     */
    start_time: Date;
    /**
     * End Time
     *
     * 경매 종료 시간, 'start_time' 시간보다 앞서 있으면 안됩니다.
     */
    end_time: Date;
    /**
     * Min Point
     *
     * 최소 입찰가
     */
    min_point?: number;
};

/**
 * KaraokeFinalBidResponse
 */
export type KaraokeFinalBidResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Auction Id
     */
    auction_id: number;
    /**
     * Party Id
     */
    party_id: number | null;
    /**
     * Amount
     */
    amount: number;
    /**
     * Created At
     */
    created_at: Date;
    bidder: User;
};

/**
 * KaraokeInviteAction
 */
export type KaraokeInviteAction = {
    /**
     * Accept
     *
     * 초대 수락 여부
     */
    accept: boolean;
};

/**
 * KaraokeInviteCreate
 */
export type KaraokeInviteCreate = {
    /**
     * User Id
     *
     * 초대할 유저의 ID
     */
    user_id: number;
};

/**
 * KaraokeMembers
 */
export type KaraokeMembers = {
    /**
     * Party Id
     *
     * 소속된 파티의 고유 ID
     */
    party_id: number;
    /**
     * User Id
     *
     * 파티 멤버의 고유 ID
     */
    user_id: number;
    /**
     * Pending
     *
     * 멤버 참여가 수락 대기중인지 여부
     */
    pending?: boolean;
};

/**
 * KaraokePartis
 */
export type KaraokePartis = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Auction Id
     *
     * 연결된 경매의 고유 ID
     */
    auction_id: number;
    /**
     * Leader Id
     *
     * 파티 대표 유저의 고유ID
     */
    leader_id: number;
    /**
     * Dispersed
     *
     * 파티 해산 여부
     */
    dispersed?: boolean;
};

/**
 * KaraokePartyDetail
 */
export type KaraokePartyDetail = {
    /**
     * Id
     */
    id: number;
    /**
     * Auction Id
     */
    auction_id: number;
    /**
     * Leader Id
     */
    leader_id: number;
    /**
     * Dispersed
     */
    dispersed: boolean;
    leader: User;
    /**
     * Members
     *
     * 파티에 소속된 멤버 목록 (초대 수락 완료)
     */
    members: Array<User>;
    /**
     * Pending Members
     *
     * 파티에 초대되어 수락 대기중인 멤버 목록
     */
    pending_members: Array<User>;
};

/**
 * KaraokeResponse
 */
export type KaraokeResponse = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Date
     *
     * 예약 일자
     */
    date: Date;
    /**
     * Time
     *
     * 예약 시간 (1~7교시, 점심시간 8)
     */
    time: number;
    /**
     * 현재 예약 상태
     */
    status?: KaraokeStatus;
    /**
     * Start Time
     *
     * 경매 시작 시간
     */
    start_time: Date;
    /**
     * End Time
     *
     * 경매 종료 시간
     */
    end_time: Date;
    /**
     * Min Point
     *
     * 최소 입찰가
     */
    min_point?: number;
    /**
     * Highest Bid
     */
    highest_bid?: number | null;
};

/**
 * KaraokeStatus
 */
export const KaraokeStatus = {
    PENDING: 'Pending',
    IN_PROGRESS: 'In_Progress',
    CONFIRMED: 'Confirmed'
} as const;

/**
 * KaraokeStatus
 */
export type KaraokeStatus = typeof KaraokeStatus[keyof typeof KaraokeStatus];

/**
 * Karaokes
 */
export type Karaokes = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Date
     *
     * 예약 일자
     */
    date: Date;
    /**
     * Time
     *
     * 예약 시간 (1~7교시, 점심시간 8)
     */
    time: number;
    /**
     * 현재 예약 상태
     */
    status?: KaraokeStatus;
    /**
     * Start Time
     *
     * 경매 시작 시간
     */
    start_time: Date;
    /**
     * End Time
     *
     * 경매 종료 시간
     */
    end_time: Date;
    /**
     * Min Point
     *
     * 최소 입찰가
     */
    min_point?: number;
};

/**
 * LoginForm
 */
export type LoginForm = {
    /**
     * Id
     */
    id: number;
    /**
     * Password
     */
    password: string;
};

/**
 * PointHistory
 */
export type PointHistory = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Changed Amount
     *
     * 변경된 포인트의 정도
     */
    changed_amount: number;
    /**
     * Reason
     *
     * 누구의 무엇의 의해서 포인트가 변경되었는지 이유
     */
    reason: string;
    /**
     * Memo
     *
     * 포인트가 어떠한 사유로 변경되었는지 이유
     */
    memo?: string | null;
    /**
     * 기록 종류
     */
    type?: PointHistoryType | null;
    /**
     * Created At
     */
    created_at?: Date;
};

/**
 * PointHistoryType
 */
export const PointHistoryType = {
    TEACHER: 'teacher',
    CAFE: 'cafe',
    FOOD: 'food',
    ETC: 'etc',
    GRANT: 'grant',
    QUEST: 'quest',
    STAMP: 'stamp',
    STAMP_BONUS: 'stamp_bonus',
    KARAOKE_BID: 'karaoke_bid',
    KARAOKE_CANCEL: 'karaoke_cancel'
} as const;

/**
 * PointHistoryType
 */
export type PointHistoryType = typeof PointHistoryType[keyof typeof PointHistoryType];

/**
 * PointOperation
 */
export type PointOperation = {
    /**
     * Target User Id
     */
    target_user_id: number;
    /**
     * Amount
     *
     * 처리할 포인트
     */
    amount: number;
    /**
     * 포인트를 처리하는 이유의 종류
     */
    change_type?: PointHistoryType | null;
    /**
     * Memo
     *
     * 포인트를 처리하는 이유
     */
    memo?: string | null;
};

/**
 * PostCreateRequest
 */
export type PostCreateRequest = {
    /**
     * Title
     *
     * 게시글 제목
     */
    title: string;
    /**
     * Content Data
     *
     * 게시글의 본문 데이터
     */
    content_data: {
        [key: string]: unknown;
    };
};

/**
 * PostUpdateRequest
 */
export type PostUpdateRequest = {
    /**
     * Title
     *
     * 수정할 게시글 제목
     */
    title?: string | null;
    /**
     * Content Data
     *
     * 수정할 게시글의 본문 데이터
     */
    content_data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Posts
 */
export type Posts = {
    /**
     * Id
     *
     * 게시글 고유 ID
     */
    id?: number | null;
    /**
     * Title
     *
     * 게시글 제목
     */
    title: string;
    /**
     * Views
     *
     * 게시글 조회수
     */
    views?: number;
    /**
     * Created At
     *
     * 게시글이 작성된 시간
     */
    created_at?: Date;
    /**
     * Updated At
     *
     * 게시글이 수정된 마지막 시간
     */
    updated_at?: Date;
    /**
     * Author Id
     *
     * 게시글 작성자의 고유 ID
     */
    author_id: number;
};

/**
 * QuestOperation
 */
export type QuestOperation = {
    /**
     * Title
     *
     * 퀘스트 제목
     */
    title: string;
    /**
     * Description
     *
     * 퀘스트 내용
     */
    description: string;
    /**
     * Reward
     *
     * 퀘스트 보상(포인트)
     */
    reward: number;
    /**
     * End Date
     *
     * 퀘스트 종료 날짜
     */
    end_date: Date;
    /**
     * Max Repeat
     *
     * 퀘스트 반복 가능 횟수
     */
    max_repeat: number;
};

/**
 * QuestUpdate
 */
export type QuestUpdate = {
    /**
     * Title
     *
     * 퀘스트 제목
     */
    title?: string | null;
    /**
     * Description
     *
     * 퀘스트 내용
     */
    description?: string | null;
    /**
     * Reward
     *
     * 퀘스트 보상(포인트)
     */
    reward?: number | null;
    /**
     * End Date
     *
     * 퀘스트 종료 날짜
     */
    end_date?: Date | null;
    /**
     * Max Repeat
     *
     * 퀘스트 반복 가능 횟수
     */
    max_repeat?: number | null;
};

/**
 * Quests
 */
export type Quests = {
    /**
     * Id
     *
     * 퀘스트 고유 ID
     */
    id?: number | null;
    /**
     * Title
     *
     * 퀘스트 제목
     */
    title: string;
    /**
     * Description
     *
     * 퀘스트 내용
     */
    description: string;
    /**
     * Reward
     *
     * 퀘스트 보상 포인트
     */
    reward: number;
    /**
     * End Date
     *
     * 퀘스트 종료 날짜
     */
    end_date: Date;
    /**
     * Max Repeat
     *
     * 학생 당 최대 반복 완료 횟수
     */
    max_repeat?: number;
    /**
     * Created At
     *
     * 퀘스트를 작성한 시간
     */
    created_at?: Date;
    /**
     * Author Id
     *
     * 퀘스트 생성 유저의 고유 ID
     */
    author_id: number;
};

/**
 * RankingResponse
 */
export type RankingResponse = {
    /**
     * Id
     *
     * 고유 ID. 교사, 서비스의 경우 자동생성. 학생의 경우 학번 사용
     */
    id: number;
    /**
     * Name
     *
     * 이름
     */
    name: string;
    /**
     * Grade
     *
     * 학년
     */
    grade: number | null;
    /**
     * Number
     *
     * 반
     */
    number: number | null;
    /**
     * Total Point
     *
     * 누적 포인트
     */
    total_point: number;
    /**
     * Rank
     *
     * 현재 순위
     */
    rank: number;
};

/**
 * ResponseModel[GetLimitResponse]
 */
export type ResponseModelGetLimitResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: GetLimitResponse;
};

/**
 * ResponseModel[KaraokeBids]
 */
export type ResponseModelKaraokeBids = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: KaraokeBids;
};

/**
 * ResponseModel[KaraokeFinalBidResponse]
 */
export type ResponseModelKaraokeFinalBidResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: KaraokeFinalBidResponse;
};

/**
 * ResponseModel[KaraokePartis]
 */
export type ResponseModelKaraokePartis = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: KaraokePartis;
};

/**
 * ResponseModel[KaraokePartyDetail]
 */
export type ResponseModelKaraokePartyDetail = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: KaraokePartyDetail;
};

/**
 * ResponseModel[KaraokeResponse]
 */
export type ResponseModelKaraokeResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: KaraokeResponse;
};

/**
 * ResponseModel[Karaokes]
 */
export type ResponseModelKaraokes = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: Karaokes;
};

/**
 * ResponseModel[PointHistory]
 */
export type ResponseModelPointHistory = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: PointHistory;
};

/**
 * ResponseModel[Posts]
 */
export type ResponseModelPosts = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: Posts;
};

/**
 * ResponseModel[Quests]
 */
export type ResponseModelQuests = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: Quests;
};

/**
 * ResponseModel[User]
 */
export type ResponseModelUser = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: User;
};

/**
 * ResponseModel[bool]
 */
export type ResponseModelBool = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: boolean;
};

/**
 * ResponseModel[int]
 */
export type ResponseModelInt = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: number;
};

/**
 * ResponseModel[list[KaraokeMembers]]
 */
export type ResponseModelListKaraokeMembers = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<KaraokeMembers>;
};

/**
 * ResponseModel[list[KaraokeResponse]]
 */
export type ResponseModelListKaraokeResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<KaraokeResponse>;
};

/**
 * ResponseModel[list[PointHistory]]
 */
export type ResponseModelListPointHistory = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<PointHistory>;
};

/**
 * ResponseModel[list[Posts]]
 */
export type ResponseModelListPosts = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<Posts>;
};

/**
 * ResponseModel[list[Quests]]
 */
export type ResponseModelListQuests = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<Quests>;
};

/**
 * ResponseModel[list[RankingResponse]]
 */
export type ResponseModelListRankingResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<RankingResponse>;
};

/**
 * ResponseModel[list[StampsList]]
 */
export type ResponseModelListStampsList = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<StampsList>;
};

/**
 * ResponseModel[list[User]]
 */
export type ResponseModelListUser = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<User>;
};

/**
 * StampCreate
 */
export type StampCreate = {
    /**
     * User Id
     */
    user_id: number;
    stamp_type: StampType;
};

/**
 * StampType
 *
 * 스탬프 종류 Enum
 * - 부스 이름은 추후 수정될 수 있습니다.
 */
export const StampType = {
    쓰레기_투호: '쓰레기 투호',
    철권_한판: '철권 한판',
    큐피트의_다트: '큐피트의 다트',
    '제기찰겨?_날찰겨?': '제기찰겨? 날찰겨?',
    팔씨름_최강자전: '팔씨름 최강자전',
    부적꾸미기: '부적꾸미기',
    누르기_챌린지: '누르기 챌린지',
    공놀이_괴물: '공놀이 괴물',
    철면피_노래방: '철면피 노래방',
    절대음감: '절대음감',
    런닝맨: '런닝맨',
    의자뺏기: '의자뺏기',
    단체줄넘기: '단체줄넘기',
    수학_키캡: '수학 키캡'
} as const;

/**
 * StampType
 *
 * 스탬프 종류 Enum
 * - 부스 이름은 추후 수정될 수 있습니다.
 */
export type StampType = typeof StampType[keyof typeof StampType];

/**
 * StampsList
 */
export type StampsList = {
    /**
     * Stamp
     */
    stamp: string;
    /**
     * Name
     */
    name: string;
    /**
     * Have
     */
    have: boolean;
    /**
     * Time
     */
    time: Date | null;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     *
     * 고유 ID. 교사, 서비스의 경우 자동생성. 학생의 경우 학번 사용
     */
    id?: number | null;
    /**
     * 유저 종류 (학생, 교사, 서비스)
     */
    type: UserType;
    /**
     * Name
     *
     * 이름
     */
    name: string;
    /**
     * Grade
     *
     * 학년
     */
    grade: number | null;
    /**
     * Number
     *
     * 반
     */
    number: number | null;
    /**
     * Point
     *
     * 보유 포인트
     */
    point?: number;
    /**
     * Total Point
     *
     * 누적 포인트
     */
    total_point?: number;
    /**
     * Permissions
     *
     * 사용자 권한
     */
    permissions?: number;
    /**
     * 해당 유저가 포인트 지급/차감시 포인트 기록 타입
     */
    history_type?: PointHistoryType | null;
};

/**
 * UserPermission
 *
 * 유저 권한 IntFlag.
 * 작명시 `동사_목적`으로 작성하며, 대문자로만 작성한다.
 * 예) 포인트 관리 -> MANAGE_POINT
 */
export const UserPermission = {
    /**
     * NONE
     */
    NONE: 0,
    /**
     * SEARCH_USER
     */
    SEARCH_USER: 131072,
    /**
     * _DEDUCT_POINT
     */
    _DEDUCT_POINT: 1,
    /**
     * DEDUCT_POINT
     */
    DEDUCT_POINT: 131073,
    /**
     * _GRANT_POINT
     */
    _GRANT_POINT: 2,
    /**
     * GRANT_POINT
     */
    GRANT_POINT: 131074,
    /**
     * NO_LIMIT_POINT
     */
    NO_LIMIT_POINT: 4,
    /**
     * CREATE_QUEST
     */
    CREATE_QUEST: 8,
    /**
     * MANAGE_QUEST
     */
    MANAGE_QUEST: 16,
    /**
     * _GIVE_STAMP
     */
    _GIVE_STAMP: 32,
    /**
     * GIVE_STAMP
     */
    GIVE_STAMP: 131104,
    /**
     * VIEW_RANK
     */
    VIEW_RANK: 64,
    /**
     * VIEW_POINT
     */
    VIEW_POINT: 128,
    /**
     * VIEW_POINT_HISTORY
     */
    VIEW_POINT_HISTORY: 256,
    /**
     * MANAGE_POST
     */
    MANAGE_POST: 512,
    /**
     * CREATE_POST
     */
    CREATE_POST: 1024,
    /**
     * _VIEW_USER_POINT
     */
    _VIEW_USER_POINT: 2048,
    /**
     * VIEW_USER_POINT
     */
    VIEW_USER_POINT: 133120,
    /**
     * JOIN_QUEST
     */
    JOIN_QUEST: 4096,
    /**
     * _MANAGE_USER
     */
    _MANAGE_USER: 8192,
    /**
     * MANAGE_USER
     */
    MANAGE_USER: 139264,
    /**
     * VIEW_POST
     */
    VIEW_POST: 16384,
    /**
     * VIEW_STAMP
     */
    VIEW_STAMP: 32768,
    /**
     * VIEW_QUEST
     */
    VIEW_QUEST: 65536,
    /**
     * JOIN_KARAOKE
     */
    JOIN_KARAOKE: 262144,
    /**
     * MANAGE_KARAOKE
     */
    MANAGE_KARAOKE: 524288,
    /**
     * VIEW_KARAOKE
     */
    VIEW_KARAOKE: 1048576,
    /**
     * STUDENT
     */
    STUDENT: 1561024,
    /**
     * TEACHER
     */
    TEACHER: 182730,
    /**
     * ADMIN
     */
    ADMIN: 665104
} as const;

/**
 * UserPermission
 *
 * 유저 권한 IntFlag.
 * 작명시 `동사_목적`으로 작성하며, 대문자로만 작성한다.
 * 예) 포인트 관리 -> MANAGE_POINT
 */
export type UserPermission = typeof UserPermission[keyof typeof UserPermission];

/**
 * UserType
 */
export const UserType = {
    STUDENT: 'student',
    TEACHER: 'teacher',
    SERVICE: 'service'
} as const;

/**
 * UserType
 */
export type UserType = typeof UserType[keyof typeof UserType];

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         *
         */
        _?: UserPermission | null;
    };
    url: '/';
};

export type ReadRootGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRootGetError = ReadRootGetErrors[keyof ReadRootGetErrors];

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginAuthLoginPostData = {
    body: LoginForm;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * ID 또는 비밀번호가 일치하지 않습니다.
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * 정상적으로 로그인이 되었음
     */
    200: ResponseModelUser;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * 정상적으로 로그아웃이 되었음
     */
    204: void;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type GetCurrentUserAuthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth';
};

export type GetCurrentUserAuthGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음.
     */
    401: ErrorResponse;
};

export type GetCurrentUserAuthGetError = GetCurrentUserAuthGetErrors[keyof GetCurrentUserAuthGetErrors];

export type GetCurrentUserAuthGetResponses = {
    /**
     * 세션이 정상적으로 유효함
     */
    200: ResponseModelUser;
};

export type GetCurrentUserAuthGetResponse = GetCurrentUserAuthGetResponses[keyof GetCurrentUserAuthGetResponses];

export type ChangePasswordNewAuthPasswordPostData = {
    body: ChangePasswordNewForm;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type ChangePasswordNewAuthPasswordPostErrors = {
    /**
     * 이미 비밀번호가 설정되어있음.
     */
    400: ErrorResponse;
    /**
     * 유저을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordNewAuthPasswordPostError = ChangePasswordNewAuthPasswordPostErrors[keyof ChangePasswordNewAuthPasswordPostErrors];

export type ChangePasswordNewAuthPasswordPostResponses = {
    /**
     * 비밀번호 변경 성공
     */
    204: void;
};

export type ChangePasswordNewAuthPasswordPostResponse = ChangePasswordNewAuthPasswordPostResponses[keyof ChangePasswordNewAuthPasswordPostResponses];

export type ChangePasswordAuthPasswordPutData = {
    body: ChangePasswordForm;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type ChangePasswordAuthPasswordPutErrors = {
    /**
     * 기존 비밀번호가 일치하지 않음
     */
    400: ErrorResponse;
    /**
     * 세션이 만료되었거나 유효하지 않음.
     */
    401: ErrorResponse;
    /**
     * 초기회 되지 않은 유저.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordAuthPasswordPutError = ChangePasswordAuthPasswordPutErrors[keyof ChangePasswordAuthPasswordPutErrors];

export type ChangePasswordAuthPasswordPutResponses = {
    /**
     * 비밀번호 변경 성공
     */
    204: void;
};

export type ChangePasswordAuthPasswordPutResponse = ChangePasswordAuthPasswordPutResponses[keyof ChangePasswordAuthPasswordPutResponses];

export type CheckPasswordExistsAuthPasswordExistsUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: {
        /**
         * T
         */
        t?: UserType | null;
    };
    url: '/auth/password/exists/{user_id}';
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetErrors = {
    /**
     * 해당 유저의 타입이 지정된 타입과 일치하지 않음
     */
    400: ErrorResponse;
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetError = CheckPasswordExistsAuthPasswordExistsUserIdGetErrors[keyof CheckPasswordExistsAuthPasswordExistsUserIdGetErrors];

export type CheckPasswordExistsAuthPasswordExistsUserIdGetResponses = {
    /**
     * 정상 조회
     */
    200: ResponseModelBool;
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetResponse = CheckPasswordExistsAuthPasswordExistsUserIdGetResponses[keyof CheckPasswordExistsAuthPasswordExistsUserIdGetResponses];

export type GetLimitPointLimitTargetUserIdGetData = {
    body?: never;
    path: {
        /**
         * Target User Id
         */
        target_user_id: number;
    };
    query?: never;
    url: '/point/limit/{target_user_id}';
};

export type GetLimitPointLimitTargetUserIdGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLimitPointLimitTargetUserIdGetError = GetLimitPointLimitTargetUserIdGetErrors[keyof GetLimitPointLimitTargetUserIdGetErrors];

export type GetLimitPointLimitTargetUserIdGetResponses = {
    /**
     * 정상적으로 처리됨
     */
    200: ResponseModelGetLimitResponse;
};

export type GetLimitPointLimitTargetUserIdGetResponse = GetLimitPointLimitTargetUserIdGetResponses[keyof GetLimitPointLimitTargetUserIdGetResponses];

export type GetLimitSessionPointLimitGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/point/limit';
};

export type GetLimitSessionPointLimitGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
};

export type GetLimitSessionPointLimitGetError = GetLimitSessionPointLimitGetErrors[keyof GetLimitSessionPointLimitGetErrors];

export type GetLimitSessionPointLimitGetResponses = {
    /**
     * 정상적으로 처리됨
     */
    200: ResponseModelInt;
};

export type GetLimitSessionPointLimitGetResponse = GetLimitSessionPointLimitGetResponses[keyof GetLimitSessionPointLimitGetResponses];

export type GrantPointsPointGrantPostData = {
    body: PointOperation;
    path?: never;
    query?: never;
    url: '/point/grant';
};

export type GrantPointsPointGrantPostErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 지급할 학생을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * 주간 포인트 지급 한도를 초과할 경우 발생합니다. 관리자 계정의 경우 한도가 적용되지 않습니다.
     */
    429: ErrorResponse;
};

export type GrantPointsPointGrantPostError = GrantPointsPointGrantPostErrors[keyof GrantPointsPointGrantPostErrors];

export type GrantPointsPointGrantPostResponses = {
    /**
     * 정상적으로 지급이 되었음
     */
    204: void;
};

export type GrantPointsPointGrantPostResponse = GrantPointsPointGrantPostResponses[keyof GrantPointsPointGrantPostResponses];

export type DeductPointsPointDeductPostData = {
    body: PointOperation;
    path?: never;
    query?: never;
    url: '/point/deduct';
};

export type DeductPointsPointDeductPostErrors = {
    /**
     * 포인트 부족
     */
    400: ErrorResponse;
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 차감할 학생을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeductPointsPointDeductPostError = DeductPointsPointDeductPostErrors[keyof DeductPointsPointDeductPostErrors];

export type DeductPointsPointDeductPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInt;
    /**
     * 정상적으로 차감이 되었음
     */
    204: void;
};

export type DeductPointsPointDeductPostResponse = DeductPointsPointDeductPostResponses[keyof DeductPointsPointDeductPostResponses];

export type GetHistoryListPointHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/point/history';
};

export type GetHistoryListPointHistoryGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHistoryListPointHistoryGetError = GetHistoryListPointHistoryGetErrors[keyof GetHistoryListPointHistoryGetErrors];

export type GetHistoryListPointHistoryGetResponses = {
    /**
     * 정상처리
     */
    200: ResponseModelListPointHistory;
};

export type GetHistoryListPointHistoryGetResponse = GetHistoryListPointHistoryGetResponses[keyof GetHistoryListPointHistoryGetResponses];

export type GetHistoryPointHistoryTargetIdGetData = {
    body?: never;
    path: {
        /**
         * Target Id
         */
        target_id: number;
    };
    query?: never;
    url: '/point/history/{target_id}';
};

export type GetHistoryPointHistoryTargetIdGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 포인트 기록을 볼 권한이 없습니다.
     */
    403: ErrorResponse;
    /**
     * 포인트 기록을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetHistoryPointHistoryTargetIdGetError = GetHistoryPointHistoryTargetIdGetErrors[keyof GetHistoryPointHistoryTargetIdGetErrors];

export type GetHistoryPointHistoryTargetIdGetResponses = {
    /**
     * 정상처리
     */
    200: ResponseModelPointHistory;
};

export type GetHistoryPointHistoryTargetIdGetResponse = GetHistoryPointHistoryTargetIdGetResponses[keyof GetHistoryPointHistoryTargetIdGetResponses];

export type GetStudentRankingPointRankingStudentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/point/ranking/student';
};

export type GetStudentRankingPointRankingStudentGetErrors = {
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudentRankingPointRankingStudentGetError = GetStudentRankingPointRankingStudentGetErrors[keyof GetStudentRankingPointRankingStudentGetErrors];

export type GetStudentRankingPointRankingStudentGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelListRankingResponse;
};

export type GetStudentRankingPointRankingStudentGetResponse = GetStudentRankingPointRankingStudentGetResponses[keyof GetStudentRankingPointRankingStudentGetResponses];

export type GetTeacherRankingPointRankingTeacherGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/point/ranking/teacher';
};

export type GetTeacherRankingPointRankingTeacherGetErrors = {
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeacherRankingPointRankingTeacherGetError = GetTeacherRankingPointRankingTeacherGetErrors[keyof GetTeacherRankingPointRankingTeacherGetErrors];

export type GetTeacherRankingPointRankingTeacherGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelListRankingResponse;
};

export type GetTeacherRankingPointRankingTeacherGetResponse = GetTeacherRankingPointRankingTeacherGetResponses[keyof GetTeacherRankingPointRankingTeacherGetResponses];

export type GetPointBalancePointTargetUserIdGetData = {
    body?: never;
    path: {
        /**
         * Target User Id
         */
        target_user_id: number;
    };
    query?: never;
    url: '/point/{target_user_id}';
};

export type GetPointBalancePointTargetUserIdGetErrors = {
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPointBalancePointTargetUserIdGetError = GetPointBalancePointTargetUserIdGetErrors[keyof GetPointBalancePointTargetUserIdGetErrors];

export type GetPointBalancePointTargetUserIdGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelInt;
};

export type GetPointBalancePointTargetUserIdGetResponse = GetPointBalancePointTargetUserIdGetResponses[keyof GetPointBalancePointTargetUserIdGetResponses];

export type SearchSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * T
         */
        t?: Array<UserType> | null;
    };
    url: '/search';
};

export type SearchSearchGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchSearchGetError = SearchSearchGetErrors[keyof SearchSearchGetErrors];

export type SearchSearchGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelListUser;
};

export type SearchSearchGetResponse = SearchSearchGetResponses[keyof SearchSearchGetResponses];

export type TeacherGetByNameSearchTeacherUserNameGetData = {
    body?: never;
    path: {
        /**
         * User Name
         */
        user_name: string;
    };
    query?: never;
    url: '/search/teacher/{user_name}';
};

export type TeacherGetByNameSearchTeacherUserNameGetErrors = {
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeacherGetByNameSearchTeacherUserNameGetError = TeacherGetByNameSearchTeacherUserNameGetErrors[keyof TeacherGetByNameSearchTeacherUserNameGetErrors];

export type TeacherGetByNameSearchTeacherUserNameGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelUser;
};

export type TeacherGetByNameSearchTeacherUserNameGetResponse = TeacherGetByNameSearchTeacherUserNameGetResponses[keyof TeacherGetByNameSearchTeacherUserNameGetResponses];

export type GetUsersAdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 페이지 번호
         */
        page?: number;
        /**
         * Size
         *
         * 페이지 당 유저 데이터 갯수 (최대 100)
         */
        size?: number;
        /**
         * User Type
         *
         * 유저 타입 필터 (student, teacher, service)
         */
        user_type?: UserType | null;
        /**
         * Permission
         *
         * 유저 권한 필터 (해당 권한을 포함하는 유저 검색)
         */
        permission?: number | null;
    };
    url: '/admin/users';
};

export type GetUsersAdminUsersGetErrors = {
    /**
     * 권한 거부
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersAdminUsersGetError = GetUsersAdminUsersGetErrors[keyof GetUsersAdminUsersGetErrors];

export type GetUsersAdminUsersGetResponses = {
    /**
     * 정상적으로 처리 됨
     */
    200: ResponseModelListUser;
};

export type GetUsersAdminUsersGetResponse = GetUsersAdminUsersGetResponses[keyof GetUsersAdminUsersGetResponses];

export type UpdateUsersPointAdminPointPostData = {
    body: AdminPointRequest;
    path?: never;
    query?: never;
    url: '/admin/point';
};

export type UpdateUsersPointAdminPointPostErrors = {
    /**
     * 권한 거부
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUsersPointAdminPointPostError = UpdateUsersPointAdminPointPostErrors[keyof UpdateUsersPointAdminPointPostErrors];

export type UpdateUsersPointAdminPointPostResponses = {
    /**
     * 정상 처리
     */
    204: void;
};

export type UpdateUsersPointAdminPointPostResponse = UpdateUsersPointAdminPointPostResponses[keyof UpdateUsersPointAdminPointPostResponses];

export type CreateUserAdminUserPostData = {
    body: AdminUserCreateRequest;
    path?: never;
    query?: never;
    url: '/admin/user';
};

export type CreateUserAdminUserPostErrors = {
    /**
     * Invalid request parameters
     */
    400: ErrorResponse;
    /**
     * Permission denied
     */
    403: ErrorResponse;
    /**
     * User already exists (e.g., duplicated student ID)
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserAdminUserPostError = CreateUserAdminUserPostErrors[keyof CreateUserAdminUserPostErrors];

export type CreateUserAdminUserPostResponses = {
    /**
     * 사용자 생성 완료
     */
    201: ResponseModelUser;
};

export type CreateUserAdminUserPostResponse = CreateUserAdminUserPostResponses[keyof CreateUserAdminUserPostResponses];

export type ResetUserPasswordAdminUsersUserIdPasswordPatchData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/admin/users/{user_id}/password';
};

export type ResetUserPasswordAdminUsersUserIdPasswordPatchErrors = {
    /**
     * Permission denied
     */
    403: ErrorResponse;
    /**
     * User not found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetUserPasswordAdminUsersUserIdPasswordPatchError = ResetUserPasswordAdminUsersUserIdPasswordPatchErrors[keyof ResetUserPasswordAdminUsersUserIdPasswordPatchErrors];

export type ResetUserPasswordAdminUsersUserIdPasswordPatchResponses = {
    /**
     * 정상 처리 (비밀번호 초기화됨)
     */
    204: void;
};

export type ResetUserPasswordAdminUsersUserIdPasswordPatchResponse = ResetUserPasswordAdminUsersUserIdPasswordPatchResponses[keyof ResetUserPasswordAdminUsersUserIdPasswordPatchResponses];

export type DeleteUserAdminUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/admin/users/{user_id}';
};

export type DeleteUserAdminUsersUserIdDeleteErrors = {
    /**
     * Permission denied
     */
    403: ErrorResponse;
    /**
     * User not found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserAdminUsersUserIdDeleteError = DeleteUserAdminUsersUserIdDeleteErrors[keyof DeleteUserAdminUsersUserIdDeleteErrors];

export type DeleteUserAdminUsersUserIdDeleteResponses = {
    /**
     * 정상 처리
     */
    204: void;
};

export type DeleteUserAdminUsersUserIdDeleteResponse = DeleteUserAdminUsersUserIdDeleteResponses[keyof DeleteUserAdminUsersUserIdDeleteResponses];

export type UpdateUserAdminUsersUserIdPatchData = {
    body: AdminUserUpdateRequest;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/admin/users/{user_id}';
};

export type UpdateUserAdminUsersUserIdPatchErrors = {
    /**
     * Invalid request parameters
     */
    400: ErrorResponse;
    /**
     * Permission denied
     */
    403: ErrorResponse;
    /**
     * User not found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserAdminUsersUserIdPatchError = UpdateUserAdminUsersUserIdPatchErrors[keyof UpdateUserAdminUsersUserIdPatchErrors];

export type UpdateUserAdminUsersUserIdPatchResponses = {
    /**
     * 사용자 정보 수정 완료
     */
    200: ResponseModelUser;
};

export type UpdateUserAdminUsersUserIdPatchResponse = UpdateUserAdminUsersUserIdPatchResponses[keyof UpdateUserAdminUsersUserIdPatchResponses];

export type CreateQuestQuestCreatePostData = {
    body: QuestOperation;
    path?: never;
    query?: never;
    url: '/quest/create';
};

export type CreateQuestQuestCreatePostErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * 퀘스트 보상 한도 초과
     */
    429: ErrorResponse;
};

export type CreateQuestQuestCreatePostError = CreateQuestQuestCreatePostErrors[keyof CreateQuestQuestCreatePostErrors];

export type CreateQuestQuestCreatePostResponses = {
    /**
     * 퀘스트 생성 성공
     */
    201: ResponseModelQuests;
};

export type CreateQuestQuestCreatePostResponse = CreateQuestQuestCreatePostResponses[keyof CreateQuestQuestCreatePostResponses];

export type ListQuestsQuestGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/quest';
};

export type ListQuestsQuestGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListQuestsQuestGetError = ListQuestsQuestGetErrors[keyof ListQuestsQuestGetErrors];

export type ListQuestsQuestGetResponses = {
    /**
     * 퀘스트 목록 조회 성공
     */
    200: ResponseModelListQuests;
};

export type ListQuestsQuestGetResponse = ListQuestsQuestGetResponses[keyof ListQuestsQuestGetResponses];

export type DeleteQuestQuestQuestIdDeleteData = {
    body?: never;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}';
};

export type DeleteQuestQuestQuestIdDeleteErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteQuestQuestQuestIdDeleteError = DeleteQuestQuestQuestIdDeleteErrors[keyof DeleteQuestQuestQuestIdDeleteErrors];

export type DeleteQuestQuestQuestIdDeleteResponses = {
    /**
     * 퀘스트 삭제 성공
     */
    204: void;
};

export type DeleteQuestQuestQuestIdDeleteResponse = DeleteQuestQuestQuestIdDeleteResponses[keyof DeleteQuestQuestQuestIdDeleteResponses];

export type GetQuestQuestQuestIdGetData = {
    body?: never;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}';
};

export type GetQuestQuestQuestIdGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestQuestQuestIdGetError = GetQuestQuestQuestIdGetErrors[keyof GetQuestQuestQuestIdGetErrors];

export type GetQuestQuestQuestIdGetResponses = {
    /**
     * 퀘스트 조회 성공
     */
    200: ResponseModelQuests;
};

export type GetQuestQuestQuestIdGetResponse = GetQuestQuestQuestIdGetResponses[keyof GetQuestQuestQuestIdGetResponses];

export type UpdateQuestQuestQuestIdPutData = {
    body: QuestUpdate;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}';
};

export type UpdateQuestQuestQuestIdPutErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * 퀘스트 보상 한도 초과
     */
    429: ErrorResponse;
};

export type UpdateQuestQuestQuestIdPutError = UpdateQuestQuestQuestIdPutErrors[keyof UpdateQuestQuestQuestIdPutErrors];

export type UpdateQuestQuestQuestIdPutResponses = {
    /**
     * 퀘스트 수정 성공
     */
    200: ResponseModelQuests;
};

export type UpdateQuestQuestQuestIdPutResponse = UpdateQuestQuestQuestIdPutResponses[keyof UpdateQuestQuestQuestIdPutResponses];

export type CompleteQuestQuestQuestIdCompletePostData = {
    body?: never;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}/complete';
};

export type CompleteQuestQuestQuestIdCompletePostErrors = {
    /**
     * 퀘스트 완료 불가
     */
    400: ErrorResponse;
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * 퀘스트 반복 한도 초과
     */
    429: ErrorResponse;
};

export type CompleteQuestQuestQuestIdCompletePostError = CompleteQuestQuestQuestIdCompletePostErrors[keyof CompleteQuestQuestQuestIdCompletePostErrors];

export type CompleteQuestQuestQuestIdCompletePostResponses = {
    /**
     * 퀘스트 완료 처리 성공
     */
    200: ResponseModelInt;
};

export type CompleteQuestQuestQuestIdCompletePostResponse = CompleteQuestQuestQuestIdCompletePostResponses[keyof CompleteQuestQuestQuestIdCompletePostResponses];

export type GetPostsPostsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 페이지 번호
         */
        page?: number;
        /**
         * Size
         *
         * 페이지 당 게시글 데이터 갯수 (최대 100)
         */
        size?: number;
    };
    url: '/posts';
};

export type GetPostsPostsGetErrors = {
    /**
     * 인증되지 않은 사용자
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostsPostsGetError = GetPostsPostsGetErrors[keyof GetPostsPostsGetErrors];

export type GetPostsPostsGetResponses = {
    /**
     * 게시글 목록 조회 성공
     */
    200: ResponseModelListPosts;
};

export type GetPostsPostsGetResponse = GetPostsPostsGetResponses[keyof GetPostsPostsGetResponses];

export type CreatePostPostsPostData = {
    body: PostCreateRequest;
    path?: never;
    query?: never;
    url: '/posts';
};

export type CreatePostPostsPostErrors = {
    /**
     * 인증되지 않은 사용자
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePostPostsPostError = CreatePostPostsPostErrors[keyof CreatePostPostsPostErrors];

export type CreatePostPostsPostResponses = {
    /**
     * 게시글 작성 완료
     */
    201: ResponseModelPosts;
};

export type CreatePostPostsPostResponse = CreatePostPostsPostResponses[keyof CreatePostPostsPostResponses];

export type DeletePostPostsPostIdDeleteData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/posts/{post_id}';
};

export type DeletePostPostsPostIdDeleteErrors = {
    /**
     * 인증되지 않은 사용자
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 게시글을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePostPostsPostIdDeleteError = DeletePostPostsPostIdDeleteErrors[keyof DeletePostPostsPostIdDeleteErrors];

export type DeletePostPostsPostIdDeleteResponses = {
    /**
     * 게시글 삭제 완료
     */
    204: void;
};

export type DeletePostPostsPostIdDeleteResponse = DeletePostPostsPostIdDeleteResponses[keyof DeletePostPostsPostIdDeleteResponses];

export type GetPostPostsPostIdGetData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/posts/{post_id}';
};

export type GetPostPostsPostIdGetErrors = {
    /**
     * 인증되지 않은 사용자
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 게시글을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostPostsPostIdGetError = GetPostPostsPostIdGetErrors[keyof GetPostPostsPostIdGetErrors];

export type GetPostPostsPostIdGetResponses = {
    /**
     * 게시글 상세 조회 성공
     */
    200: ResponseModelPosts;
};

export type GetPostPostsPostIdGetResponse = GetPostPostsPostIdGetResponses[keyof GetPostPostsPostIdGetResponses];

export type UpdatePostPostsPostIdPatchData = {
    body: PostUpdateRequest;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/posts/{post_id}';
};

export type UpdatePostPostsPostIdPatchErrors = {
    /**
     * 인증되지 않은 사용자
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 게시글을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePostPostsPostIdPatchError = UpdatePostPostsPostIdPatchErrors[keyof UpdatePostPostsPostIdPatchErrors];

export type UpdatePostPostsPostIdPatchResponses = {
    /**
     * 게시글 수정 완료
     */
    200: ResponseModelPosts;
};

export type UpdatePostPostsPostIdPatchResponse = UpdatePostPostsPostIdPatchResponses[keyof UpdatePostPostsPostIdPatchResponses];

export type GetUserStampsStampGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stamp';
};

export type GetUserStampsStampGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
};

export type GetUserStampsStampGetError = GetUserStampsStampGetErrors[keyof GetUserStampsStampGetErrors];

export type GetUserStampsStampGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelListStampsList;
};

export type GetUserStampsStampGetResponse = GetUserStampsStampGetResponses[keyof GetUserStampsStampGetResponses];

export type CreateStampStampPostData = {
    body: StampCreate;
    path?: never;
    query?: never;
    url: '/stamp';
};

export type CreateStampStampPostErrors = {
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * 이미 해당 스탬프를 발급 받음
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStampStampPostError = CreateStampStampPostErrors[keyof CreateStampStampPostErrors];

export type CreateStampStampPostResponses = {
    /**
     * 정상 처리
     */
    204: void;
};

export type CreateStampStampPostResponse = CreateStampStampPostResponses[keyof CreateStampStampPostResponses];

export type GetKaraokeListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Date
         */
        date?: Date | null;
    };
    url: '/karaoke';
};

export type GetKaraokeListErrors = {
    /**
     * 권한 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetKaraokeListError = GetKaraokeListErrors[keyof GetKaraokeListErrors];

export type GetKaraokeListResponses = {
    /**
     * 정상적으로 처리됨.
     */
    200: ResponseModelListKaraokeResponse;
};

export type GetKaraokeListResponse = GetKaraokeListResponses[keyof GetKaraokeListResponses];

export type CreateKaraokeData = {
    body: KaraokeCreate;
    path?: never;
    query?: never;
    url: '/karaoke';
};

export type CreateKaraokeErrors = {
    /**
     * 잘못된 요청 데이터
     */
    400: ErrorResponse;
    /**
     * 권한 없음
     */
    403: ErrorResponse;
    /**
     * 중복된 경매 존재
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKaraokeError = CreateKaraokeErrors[keyof CreateKaraokeErrors];

export type CreateKaraokeResponses = {
    /**
     * 정상적으로 생성이 완료됨
     */
    201: ResponseModelKaraokes;
};

export type CreateKaraokeResponse = CreateKaraokeResponses[keyof CreateKaraokeResponses];

export type DeleteKaraokeData = {
    body?: never;
    path: {
        /**
         * Karaoke Id
         */
        karaoke_id: number;
    };
    query?: never;
    url: '/karaoke/{karaoke_id}';
};

export type DeleteKaraokeErrors = {
    /**
     * 권한 없음
     */
    403: ErrorResponse;
    /**
     * 예약을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteKaraokeError = DeleteKaraokeErrors[keyof DeleteKaraokeErrors];

export type DeleteKaraokeResponses = {
    /**
     * 정상적으로 처리됨.
     */
    204: void;
};

export type DeleteKaraokeResponse = DeleteKaraokeResponses[keyof DeleteKaraokeResponses];

export type GetKaraokeData = {
    body?: never;
    path: {
        /**
         * Karaoke Id
         */
        karaoke_id: number;
    };
    query?: never;
    url: '/karaoke/{karaoke_id}';
};

export type GetKaraokeErrors = {
    /**
     * 권한 없음
     */
    403: ErrorResponse;
    /**
     * 예약을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetKaraokeError = GetKaraokeErrors[keyof GetKaraokeErrors];

export type GetKaraokeResponses = {
    /**
     * 정상적으로 처리됨.
     */
    200: ResponseModelKaraokeResponse;
};

export type GetKaraokeResponse = GetKaraokeResponses[keyof GetKaraokeResponses];

export type CreateKaraokePartyData = {
    body?: never;
    path: {
        /**
         * Karaoke Id
         */
        karaoke_id: number;
    };
    query?: never;
    url: '/karaoke/{karaoke_id}/party';
};

export type CreateKaraokePartyErrors = {
    /**
     * 파티 생성 조건 불만족 (이미 생성 등)
     */
    400: ErrorResponse;
    /**
     * 권한 없음
     */
    403: ErrorResponse;
    /**
     * 예약을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKaraokePartyError = CreateKaraokePartyErrors[keyof CreateKaraokePartyErrors];

export type CreateKaraokePartyResponses = {
    /**
     * 정상적으로 파티 생성 완료
     */
    201: ResponseModelKaraokePartis;
};

export type CreateKaraokePartyResponse = CreateKaraokePartyResponses[keyof CreateKaraokePartyResponses];

export type GetMyKaraokePartyData = {
    body?: never;
    path: {
        /**
         * Karaoke Id
         */
        karaoke_id: number;
    };
    query?: never;
    url: '/karaoke/{karaoke_id}/party/me';
};

export type GetMyKaraokePartyErrors = {
    /**
     * 권한 없음
     */
    403: ErrorResponse;
    /**
     * 예약을 찾을 수 없거나, 속한 파티가 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMyKaraokePartyError = GetMyKaraokePartyErrors[keyof GetMyKaraokePartyErrors];

export type GetMyKaraokePartyResponses = {
    /**
     * 정상적으로 처리됨.
     */
    200: ResponseModelKaraokePartyDetail;
};

export type GetMyKaraokePartyResponse = GetMyKaraokePartyResponses[keyof GetMyKaraokePartyResponses];

export type CreateKaraokeBidData = {
    body: KaraokeBidCreate;
    path: {
        /**
         * Karaoke Id
         */
        karaoke_id: number;
    };
    query?: never;
    url: '/karaoke/{karaoke_id}/bid';
};

export type CreateKaraokeBidErrors = {
    /**
     * 입찰 조건 불만족 (금액 부족 등)
     */
    400: ErrorResponse;
    /**
     * 포인트 부족
     */
    402: ErrorResponse;
    /**
     * 권한 없음
     */
    403: ErrorResponse;
    /**
     * 예약/파티를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKaraokeBidError = CreateKaraokeBidErrors[keyof CreateKaraokeBidErrors];

export type CreateKaraokeBidResponses = {
    /**
     * 정상적으로 입찰 완료
     */
    201: ResponseModelKaraokeBids;
};

export type CreateKaraokeBidResponse = CreateKaraokeBidResponses[keyof CreateKaraokeBidResponses];

export type GetKaraokeFinalBidData = {
    body?: never;
    path: {
        /**
         * Karaoke Id
         */
        karaoke_id: number;
    };
    query?: never;
    url: '/karaoke/{karaoke_id}/final-bid';
};

export type GetKaraokeFinalBidErrors = {
    /**
     * 권한 없음
     */
    403: ErrorResponse;
    /**
     * 예약을 찾을 수 없거나, 입찰 기록이 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetKaraokeFinalBidError = GetKaraokeFinalBidErrors[keyof GetKaraokeFinalBidErrors];

export type GetKaraokeFinalBidResponses = {
    /**
     * 정상적으로 처리됨.
     */
    200: ResponseModelKaraokeFinalBidResponse;
};

export type GetKaraokeFinalBidResponse = GetKaraokeFinalBidResponses[keyof GetKaraokeFinalBidResponses];

export type DisperseKaraokePartyData = {
    body?: never;
    path: {
        /**
         * Party Id
         */
        party_id: number;
    };
    query?: never;
    url: '/karaoke/party/{party_id}';
};

export type DisperseKaraokePartyErrors = {
    /**
     * 이미 해산된 파티
     */
    400: ErrorResponse;
    /**
     * 권한 없음 (파티장이 아님)
     */
    403: ErrorResponse;
    /**
     * 파티를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DisperseKaraokePartyError = DisperseKaraokePartyErrors[keyof DisperseKaraokePartyErrors];

export type DisperseKaraokePartyResponses = {
    /**
     * 정상적으로 파티 해산 완료
     */
    204: void;
};

export type DisperseKaraokePartyResponse = DisperseKaraokePartyResponses[keyof DisperseKaraokePartyResponses];

export type GetKaraokePartyData = {
    body?: never;
    path: {
        /**
         * Party Id
         */
        party_id: number;
    };
    query?: never;
    url: '/karaoke/party/{party_id}';
};

export type GetKaraokePartyErrors = {
    /**
     * 권한 없음 (파티에 소속되거나 초대받지 않음)
     */
    403: ErrorResponse;
    /**
     * 파티를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetKaraokePartyError = GetKaraokePartyErrors[keyof GetKaraokePartyErrors];

export type GetKaraokePartyResponses = {
    /**
     * 정상적으로 처리됨.
     */
    200: ResponseModelKaraokePartyDetail;
};

export type GetKaraokePartyResponse = GetKaraokePartyResponses[keyof GetKaraokePartyResponses];

export type LeaveKaraokePartyData = {
    body?: never;
    path: {
        /**
         * Party Id
         */
        party_id: number;
    };
    query?: never;
    url: '/karaoke/party/{party_id}/leave';
};

export type LeaveKaraokePartyErrors = {
    /**
     * 파티장은 탈퇴할 수 없음 (해산 API 사용 필요)
     */
    400: ErrorResponse;
    /**
     * 권한 없음
     */
    403: ErrorResponse;
    /**
     * 파티를 찾을 수 없거나, 소속된 멤버가 아님
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LeaveKaraokePartyError = LeaveKaraokePartyErrors[keyof LeaveKaraokePartyErrors];

export type LeaveKaraokePartyResponses = {
    /**
     * 정상적으로 파티 탈퇴 완료
     */
    204: void;
};

export type LeaveKaraokePartyResponse = LeaveKaraokePartyResponses[keyof LeaveKaraokePartyResponses];

export type KickKaraokePartyMemberData = {
    body?: never;
    path: {
        /**
         * Party Id
         */
        party_id: number;
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/karaoke/party/{party_id}/members/{user_id}';
};

export type KickKaraokePartyMemberErrors = {
    /**
     * 파티장은 강퇴할 수 없음
     */
    400: ErrorResponse;
    /**
     * 권한 없음 (파티장이 아님)
     */
    403: ErrorResponse;
    /**
     * 파티, 유저 또는 파티 멤버를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KickKaraokePartyMemberError = KickKaraokePartyMemberErrors[keyof KickKaraokePartyMemberErrors];

export type KickKaraokePartyMemberResponses = {
    /**
     * 정상적으로 멤버 강퇴 완료
     */
    200: ResponseModelKaraokePartyDetail;
};

export type KickKaraokePartyMemberResponse = KickKaraokePartyMemberResponses[keyof KickKaraokePartyMemberResponses];

export type InviteKaraokePartyMemberData = {
    body: KaraokeInviteCreate;
    path: {
        /**
         * Party Id
         */
        party_id: number;
    };
    query?: never;
    url: '/karaoke/party/{party_id}/invite';
};

export type InviteKaraokePartyMemberErrors = {
    /**
     * 해산된 파티이거나, 파티장 자신을 초대함
     */
    400: ErrorResponse;
    /**
     * 권한 없음 (파티장이 아님)
     */
    403: ErrorResponse;
    /**
     * 파티나 초대할 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * 이미 이 경매의 파티에 소속되었거나 초대된 유저
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InviteKaraokePartyMemberError = InviteKaraokePartyMemberErrors[keyof InviteKaraokePartyMemberErrors];

export type InviteKaraokePartyMemberResponses = {
    /**
     * 정상적으로 초대 완료
     */
    204: void;
};

export type InviteKaraokePartyMemberResponse = InviteKaraokePartyMemberResponses[keyof InviteKaraokePartyMemberResponses];

export type GetMyKaraokePartyInvitesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/karaoke/party/invites/me';
};

export type GetMyKaraokePartyInvitesResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelListKaraokeMembers;
};

export type GetMyKaraokePartyInvitesResponse = GetMyKaraokePartyInvitesResponses[keyof GetMyKaraokePartyInvitesResponses];

export type DecideKaraokePartyInviteData = {
    body: KaraokeInviteAction;
    path: {
        /**
         * Party Id
         */
        party_id: number;
    };
    query?: never;
    url: '/karaoke/party/{party_id}/action';
};

export type DecideKaraokePartyInviteErrors = {
    /**
     * 대기 중인 초대장을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DecideKaraokePartyInviteError = DecideKaraokePartyInviteErrors[keyof DecideKaraokePartyInviteErrors];

export type DecideKaraokePartyInviteResponses = {
    /**
     * 정상적으로 수락/거절 완료
     */
    200: ResponseModelBool;
};

export type DecideKaraokePartyInviteResponse = DecideKaraokePartyInviteResponses[keyof DecideKaraokePartyInviteResponses];
