// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AdminPointRequest
 */
export type AdminPointRequest = {
    /**
     * User Ids
     *
     * 포인트를 지급/차감할 대상 유저 ID 목록
     */
    user_ids: Array<number>;
    /**
     * Amount
     *
     * 변동될 포인트 (양수는 지급, 음수는 차감)
     */
    amount: number;
    /**
     * Reason
     *
     * 포인트 변동 사유
     */
    reason: string;
};

/**
 * ChangePasswordForm
 */
export type ChangePasswordForm = {
    /**
     * Old Password
     */
    old_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ChangePasswordNewForm
 */
export type ChangePasswordNewForm = {
    /**
     * User
     */
    user: number;
    /**
     * Password
     */
    password: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     *
     * 에러 메시지
     */
    message: string;
};

/**
 * GetLimitResponse
 */
export type GetLimitResponse = {
    /**
     * Limit
     */
    limit: number;
    /**
     * Target Limit
     */
    target_limit: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginForm
 */
export type LoginForm = {
    /**
     * Id
     */
    id: number;
    /**
     * Password
     */
    password: string;
};

/**
 * PointHistory
 */
export type PointHistory = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Changed Amount
     *
     * 변경된 포인트의 정도
     */
    changed_amount: number;
    /**
     * Reason
     *
     * 누구의 무엇의 의해서 포인트가 변경되었는지 이유
     */
    reason: string;
    /**
     * Memo
     *
     * 포인트가 어떠한 사유로 변경되었는지 이유
     */
    memo?: string | null;
    /**
     * 기록 종류
     */
    type?: PointHistoryType | null;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * PointHistoryType
 */
export type PointHistoryType = 'teacher' | 'cafe' | 'food' | 'etc' | 'grant' | 'quest' | 'stamp' | 'stamp_bonus';

/**
 * PointOperation
 */
export type PointOperation = {
    /**
     * Target User Id
     */
    target_user_id: number;
    /**
     * Amount
     *
     * 처리할 포인트
     */
    amount: number;
    /**
     * 포인트를 처리하는 이유의 종류
     */
    change_type?: PointHistoryType | null;
    /**
     * Memo
     *
     * 포인트를 처리하는 이유
     */
    memo?: string | null;
};

/**
 * PostCreateRequest
 */
export type PostCreateRequest = {
    /**
     * Title
     *
     * 게시글 제목
     */
    title: string;
    /**
     * Content Data
     *
     * 게시글의 본문 데이터
     */
    content_data: {
        [key: string]: unknown;
    };
};

/**
 * PostUpdateRequest
 */
export type PostUpdateRequest = {
    /**
     * Title
     *
     * 수정할 게시글 제목
     */
    title?: string | null;
    /**
     * Content Data
     *
     * 수정할 게시글의 본문 데이터
     */
    content_data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * Posts
 */
export type Posts = {
    /**
     * Id
     *
     * 게시글 고유 ID
     */
    id?: number | null;
    /**
     * Title
     *
     * 게시글 제목
     */
    title: string;
    /**
     * Views
     *
     * 게시글 조회수
     */
    views?: number;
    /**
     * Created At
     *
     * 게시글이 작성된 시간
     */
    created_at?: string;
    /**
     * Updated At
     *
     * 게시글이 수정된 마지막 시간
     */
    updated_at?: string;
    /**
     * Author Id
     *
     * 게시글 작성자의 고유 ID
     */
    author_id: number;
};

/**
 * QuestOperation
 */
export type QuestOperation = {
    /**
     * Title
     *
     * 퀘스트 제목
     */
    title: string;
    /**
     * Description
     *
     * 퀘스트 내용
     */
    description: string;
    /**
     * Reward
     *
     * 퀘스트 보상(포인트)
     */
    reward: number;
    /**
     * End Date
     *
     * 퀘스트 종료 날짜
     */
    end_date: string;
};

/**
 * QuestResponse
 */
export type QuestResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Reward
     */
    reward: number;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Author Id
     */
    author_id: number;
};

/**
 * QuestUpdate
 */
export type QuestUpdate = {
    /**
     * Title
     *
     * 퀘스트 제목
     */
    title?: string | null;
    /**
     * Description
     *
     * 퀘스트 내용
     */
    description?: string | null;
    /**
     * Reward
     *
     * 퀘스트 보상(포인트)
     */
    reward?: number | null;
    /**
     * End Date
     *
     * 퀘스트 종료 날짜
     */
    end_date?: string | null;
};

/**
 * RankingResponse
 */
export type RankingResponse = {
    /**
     * Id
     *
     * 고유 ID. 교사, 서비스의 경우 자동생성. 학생의 경우 학번 사용
     */
    id: number;
    /**
     * Name
     *
     * 이름
     */
    name: string;
    /**
     * Grade
     *
     * 학년
     */
    grade: number | null;
    /**
     * Number
     *
     * 반
     */
    number: number | null;
    /**
     * Total Point
     *
     * 누적 포인트
     */
    total_point: number;
    /**
     * Rank
     *
     * 현재 순위
     */
    rank: number;
};

/**
 * ResponseModel[GetLimitResponse]
 */
export type ResponseModelGetLimitResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: GetLimitResponse;
};

/**
 * ResponseModel[List[Posts]]
 */
export type ResponseModelListPosts = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<Posts>;
};

/**
 * ResponseModel[List[QuestResponse]]
 */
export type ResponseModelListQuestResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<QuestResponse>;
};

/**
 * ResponseModel[List[User]]
 */
export type ResponseModelListUser = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<User>;
};

/**
 * ResponseModel[List[dict]]
 */
export type ResponseModelListDict = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * ResponseModel[NoneType]
 */
export type ResponseModelNoneType = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: null;
};

/**
 * ResponseModel[Posts]
 */
export type ResponseModelPosts = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: Posts;
};

/**
 * ResponseModel[QuestResponse]
 */
export type ResponseModelQuestResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: QuestResponse;
};

/**
 * ResponseModel[User]
 */
export type ResponseModelUser = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: User;
};

/**
 * ResponseModel[bool]
 */
export type ResponseModelBool = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: boolean;
};

/**
 * ResponseModel[int]
 */
export type ResponseModelInt = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: number;
};

/**
 * ResponseModel[list[PointHistory]]
 */
export type ResponseModelListPointHistory = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<PointHistory>;
};

/**
 * ResponseModel[list[RankingResponse]]
 */
export type ResponseModelListRankingResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<RankingResponse>;
};

/**
 * ResponseModel[list[StampsList]]
 */
export type ResponseModelListStampsList = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<StampsList>;
};

/**
 * StampCreate
 */
export type StampCreate = {
    /**
     * User Id
     */
    user_id: number;
    stamp_type: StampType;
};

/**
 * StampType
 *
 * 스탬프 종류 Enum
 * - 부스 이름은 추후 수정될 수 있습니다.
 */
export type StampType = '쓰레기 투호' | '철권 한판' | '큐피트의 다트' | '제기찰겨? 날찰겨?' | '팔씨름 최강자전' | '부적꾸미기' | '누르기 챌린지' | '공놀이 괴물' | '철면피 노래방' | '절대음감' | '런닝맨' | '의자뺏기' | '단체줄넘기' | '수학 키캡';

/**
 * StampsList
 */
export type StampsList = {
    /**
     * Stamp
     */
    stamp: string;
    /**
     * Name
     */
    name: string;
    /**
     * Have
     */
    have: boolean;
    /**
     * Time
     */
    time: string | null;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     *
     * 고유 ID. 교사, 서비스의 경우 자동생성. 학생의 경우 학번 사용
     */
    id?: number | null;
    /**
     * 유저 종류 (학생, 교사, 서비스)
     */
    type: UserType;
    /**
     * Name
     *
     * 이름
     */
    name: string;
    /**
     * Grade
     *
     * 학년
     */
    grade: number | null;
    /**
     * Number
     *
     * 반
     */
    number: number | null;
    /**
     * Point
     *
     * 보유 포인트
     */
    point?: number;
    /**
     * Total Point
     *
     * 누적 포인트
     */
    total_point?: number;
    /**
     * Is Admin
     *
     * 관리자 여부
     */
    is_admin?: boolean;
    /**
     * 해당 유저가 포인트 지급/차감시 포인트 기록 타입
     */
    history_type?: PointHistoryType | null;
};

/**
 * UserType
 */
export type UserType = 'student' | 'teacher' | 'service';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginAuthLoginPostData = {
    body: LoginForm;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * ID 또는 비밀번호가 일치하지 않습니다.
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * 정상적으로 로그인이 되었음
     */
    200: ResponseModelUser;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * 정상적으로 로그아웃이 되었음
     */
    204: void;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type GetCurrentUserAuthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth';
};

export type GetCurrentUserAuthGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음.
     */
    401: ErrorResponse;
};

export type GetCurrentUserAuthGetError = GetCurrentUserAuthGetErrors[keyof GetCurrentUserAuthGetErrors];

export type GetCurrentUserAuthGetResponses = {
    /**
     * 세션이 정상적으로 유효함
     */
    200: ResponseModelUser;
};

export type GetCurrentUserAuthGetResponse = GetCurrentUserAuthGetResponses[keyof GetCurrentUserAuthGetResponses];

export type ChangePasswordNewAuthPasswordPostData = {
    body: ChangePasswordNewForm;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type ChangePasswordNewAuthPasswordPostErrors = {
    /**
     * 이미 비밀번호가 설정되어있음.
     */
    400: ErrorResponse;
    /**
     * 유저을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordNewAuthPasswordPostError = ChangePasswordNewAuthPasswordPostErrors[keyof ChangePasswordNewAuthPasswordPostErrors];

export type ChangePasswordNewAuthPasswordPostResponses = {
    /**
     * 비밀번호 변경 성공
     */
    204: void;
};

export type ChangePasswordNewAuthPasswordPostResponse = ChangePasswordNewAuthPasswordPostResponses[keyof ChangePasswordNewAuthPasswordPostResponses];

export type ChangePasswordAuthPasswordPutData = {
    body: ChangePasswordForm;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type ChangePasswordAuthPasswordPutErrors = {
    /**
     * 기존 비밀번호가 일치하지 않음
     */
    400: ErrorResponse;
    /**
     * 세션이 만료되었거나 유효하지 않음.
     */
    401: ErrorResponse;
    /**
     * 초기회 되지 않은 유저.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordAuthPasswordPutError = ChangePasswordAuthPasswordPutErrors[keyof ChangePasswordAuthPasswordPutErrors];

export type ChangePasswordAuthPasswordPutResponses = {
    /**
     * 비밀번호 변경 성공
     */
    204: void;
};

export type ChangePasswordAuthPasswordPutResponse = ChangePasswordAuthPasswordPutResponses[keyof ChangePasswordAuthPasswordPutResponses];

export type CheckPasswordExistsAuthPasswordExistsUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: {
        /**
         * T
         */
        t?: UserType | null;
    };
    url: '/auth/password/exists/{user_id}';
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetErrors = {
    /**
     * 해당 유저의 타입이 지정된 타입과 일치하지 않음
     */
    400: ErrorResponse;
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetError = CheckPasswordExistsAuthPasswordExistsUserIdGetErrors[keyof CheckPasswordExistsAuthPasswordExistsUserIdGetErrors];

export type CheckPasswordExistsAuthPasswordExistsUserIdGetResponses = {
    /**
     * 정상 조회
     */
    200: ResponseModelBool;
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetResponse = CheckPasswordExistsAuthPasswordExistsUserIdGetResponses[keyof CheckPasswordExistsAuthPasswordExistsUserIdGetResponses];

export type GetLimitPointLimitTargetUserIdGetData = {
    body?: never;
    path: {
        /**
         * Target User Id
         */
        target_user_id: number;
    };
    query?: never;
    url: '/point/limit/{target_user_id}';
};

export type GetLimitPointLimitTargetUserIdGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLimitPointLimitTargetUserIdGetError = GetLimitPointLimitTargetUserIdGetErrors[keyof GetLimitPointLimitTargetUserIdGetErrors];

export type GetLimitPointLimitTargetUserIdGetResponses = {
    /**
     * 정상적으로 처리됨
     */
    200: ResponseModelGetLimitResponse;
};

export type GetLimitPointLimitTargetUserIdGetResponse = GetLimitPointLimitTargetUserIdGetResponses[keyof GetLimitPointLimitTargetUserIdGetResponses];

export type GetLimitSessionPointLimitGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/point/limit';
};

export type GetLimitSessionPointLimitGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
};

export type GetLimitSessionPointLimitGetError = GetLimitSessionPointLimitGetErrors[keyof GetLimitSessionPointLimitGetErrors];

export type GetLimitSessionPointLimitGetResponses = {
    /**
     * 정상적으로 처리됨
     */
    200: ResponseModelInt;
};

export type GetLimitSessionPointLimitGetResponse = GetLimitSessionPointLimitGetResponses[keyof GetLimitSessionPointLimitGetResponses];

export type GrantPointsPointGrantPostData = {
    body: PointOperation;
    path?: never;
    query?: never;
    url: '/point/grant';
};

export type GrantPointsPointGrantPostErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 지급할 학생을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * 주간 포인트 지급 한도를 초과할 경우 발생합니다. 관리자 계정의 경우 한도가 적용되지 않습니다.
     */
    429: ErrorResponse;
};

export type GrantPointsPointGrantPostError = GrantPointsPointGrantPostErrors[keyof GrantPointsPointGrantPostErrors];

export type GrantPointsPointGrantPostResponses = {
    /**
     * 정상적으로 지급이 되었음
     */
    204: void;
};

export type GrantPointsPointGrantPostResponse = GrantPointsPointGrantPostResponses[keyof GrantPointsPointGrantPostResponses];

export type DeductPointsPointDeductPostData = {
    body: PointOperation;
    path?: never;
    query?: never;
    url: '/point/deduct';
};

export type DeductPointsPointDeductPostErrors = {
    /**
     * 포인트 부족
     */
    400: ErrorResponse;
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 차감할 학생을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeductPointsPointDeductPostError = DeductPointsPointDeductPostErrors[keyof DeductPointsPointDeductPostErrors];

export type DeductPointsPointDeductPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInt;
    /**
     * 정상적으로 차감이 되었음
     */
    204: void;
};

export type DeductPointsPointDeductPostResponse = DeductPointsPointDeductPostResponses[keyof DeductPointsPointDeductPostResponses];

export type PointHistoryPointHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/point/history';
};

export type PointHistoryPointHistoryGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PointHistoryPointHistoryGetError = PointHistoryPointHistoryGetErrors[keyof PointHistoryPointHistoryGetErrors];

export type PointHistoryPointHistoryGetResponses = {
    /**
     * 정상처리
     */
    200: ResponseModelListPointHistory;
};

export type PointHistoryPointHistoryGetResponse = PointHistoryPointHistoryGetResponses[keyof PointHistoryPointHistoryGetResponses];

export type GetStudentRankingPointRankingStudentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/point/ranking/student';
};

export type GetStudentRankingPointRankingStudentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudentRankingPointRankingStudentGetError = GetStudentRankingPointRankingStudentGetErrors[keyof GetStudentRankingPointRankingStudentGetErrors];

export type GetStudentRankingPointRankingStudentGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelListRankingResponse;
};

export type GetStudentRankingPointRankingStudentGetResponse = GetStudentRankingPointRankingStudentGetResponses[keyof GetStudentRankingPointRankingStudentGetResponses];

export type GetTeacherRankingPointRankingTeacherGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/point/ranking/teacher';
};

export type GetTeacherRankingPointRankingTeacherGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeacherRankingPointRankingTeacherGetError = GetTeacherRankingPointRankingTeacherGetErrors[keyof GetTeacherRankingPointRankingTeacherGetErrors];

export type GetTeacherRankingPointRankingTeacherGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelListRankingResponse;
};

export type GetTeacherRankingPointRankingTeacherGetResponse = GetTeacherRankingPointRankingTeacherGetResponses[keyof GetTeacherRankingPointRankingTeacherGetResponses];

export type GetPointBalancePointTargetUserIdGetData = {
    body?: never;
    path: {
        /**
         * Target User Id
         */
        target_user_id: number;
    };
    query?: never;
    url: '/point/{target_user_id}';
};

export type GetPointBalancePointTargetUserIdGetErrors = {
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPointBalancePointTargetUserIdGetError = GetPointBalancePointTargetUserIdGetErrors[keyof GetPointBalancePointTargetUserIdGetErrors];

export type GetPointBalancePointTargetUserIdGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelInt;
};

export type GetPointBalancePointTargetUserIdGetResponse = GetPointBalancePointTargetUserIdGetResponses[keyof GetPointBalancePointTargetUserIdGetResponses];

export type SearchSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * T
         */
        t?: Array<UserType>;
    };
    url: '/search';
};

export type SearchSearchGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchSearchGetError = SearchSearchGetErrors[keyof SearchSearchGetErrors];

export type SearchSearchGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelListUser;
};

export type SearchSearchGetResponse = SearchSearchGetResponses[keyof SearchSearchGetResponses];

export type TeacherGetByNameSearchTeacherUserNameGetData = {
    body?: never;
    path: {
        /**
         * User Name
         */
        user_name: string;
    };
    query?: never;
    url: '/search/teacher/{user_name}';
};

export type TeacherGetByNameSearchTeacherUserNameGetErrors = {
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeacherGetByNameSearchTeacherUserNameGetError = TeacherGetByNameSearchTeacherUserNameGetErrors[keyof TeacherGetByNameSearchTeacherUserNameGetErrors];

export type TeacherGetByNameSearchTeacherUserNameGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelUser;
};

export type TeacherGetByNameSearchTeacherUserNameGetResponse = TeacherGetByNameSearchTeacherUserNameGetResponses[keyof TeacherGetByNameSearchTeacherUserNameGetResponses];

export type GetUsersAdminUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 페이지 번호
         */
        page?: number;
        /**
         * Size
         *
         * 페이지 당 유저 데이터 갯수 (최대 100)
         */
        size?: number;
        /**
         * User Type
         *
         * 유저 타입 필터 (student, teacher, service)
         */
        user_type?: UserType | null;
        /**
         * Permission
         *
         * 유저 권한 필터 (해당 권한을 포함하는 유저 검색)
         */
        permission?: UserPermission | null;
    };
    url: '/admin/users';
};

export type GetUsersAdminUsersGetErrors = {
    /**
     * 권한 거부
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersAdminUsersGetError = GetUsersAdminUsersGetErrors[keyof GetUsersAdminUsersGetErrors];

export type GetUsersAdminUsersGetResponses = {
    /**
     * 정상적으로 처리 됨
     */
    200: ResponseModelListUser;
};

export type GetUsersAdminUsersGetResponse = GetUsersAdminUsersGetResponses[keyof GetUsersAdminUsersGetResponses];

export type UpdateUsersPointAdminPointPostData = {
    body: AdminPointRequest;
    path?: never;
    query?: never;
    url: '/admin/point';
};

export type UpdateUsersPointAdminPointPostErrors = {
    /**
     * 권한 거부
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUsersPointAdminPointPostError = UpdateUsersPointAdminPointPostErrors[keyof UpdateUsersPointAdminPointPostErrors];

export type UpdateUsersPointAdminPointPostResponses = {
    /**
     * 정상 처리
     */
    204: void;
};

export type UpdateUsersPointAdminPointPostResponse = UpdateUsersPointAdminPointPostResponses[keyof UpdateUsersPointAdminPointPostResponses];

export type CreateQuestQuestCreatePostData = {
    body: QuestOperation;
    path?: never;
    query?: never;
    url: '/quest/create';
};

export type CreateQuestQuestCreatePostErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * 퀘스트 보상 한도 초과
     */
    429: ErrorResponse;
};

export type CreateQuestQuestCreatePostError = CreateQuestQuestCreatePostErrors[keyof CreateQuestQuestCreatePostErrors];

export type CreateQuestQuestCreatePostResponses = {
    /**
     * 퀘스트 생성 성공
     */
    201: ResponseModelQuestResponse;
};

export type CreateQuestQuestCreatePostResponse = CreateQuestQuestCreatePostResponses[keyof CreateQuestQuestCreatePostResponses];

export type ListQuestsQuestGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/quest';
};

export type ListQuestsQuestGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListQuestsQuestGetError = ListQuestsQuestGetErrors[keyof ListQuestsQuestGetErrors];

export type ListQuestsQuestGetResponses = {
    /**
     * 퀘스트 목록 조회 성공
     */
    200: ResponseModelListQuestResponse;
};

export type ListQuestsQuestGetResponse = ListQuestsQuestGetResponses[keyof ListQuestsQuestGetResponses];

export type DeleteQuestQuestQuestIdDeleteData = {
    body?: never;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}';
};

export type DeleteQuestQuestQuestIdDeleteErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteQuestQuestQuestIdDeleteError = DeleteQuestQuestQuestIdDeleteErrors[keyof DeleteQuestQuestQuestIdDeleteErrors];

export type DeleteQuestQuestQuestIdDeleteResponses = {
    /**
     * 퀘스트 삭제 성공
     */
    204: void;
};

export type DeleteQuestQuestQuestIdDeleteResponse = DeleteQuestQuestQuestIdDeleteResponses[keyof DeleteQuestQuestQuestIdDeleteResponses];

export type GetQuestQuestQuestIdGetData = {
    body?: never;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}';
};

export type GetQuestQuestQuestIdGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestQuestQuestIdGetError = GetQuestQuestQuestIdGetErrors[keyof GetQuestQuestQuestIdGetErrors];

export type GetQuestQuestQuestIdGetResponses = {
    /**
     * 퀘스트 조회 성공
     */
    200: ResponseModelQuestResponse;
};

export type GetQuestQuestQuestIdGetResponse = GetQuestQuestQuestIdGetResponses[keyof GetQuestQuestQuestIdGetResponses];

export type UpdateQuestQuestQuestIdPutData = {
    body: QuestUpdate;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}';
};

export type UpdateQuestQuestQuestIdPutErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * 퀘스트 보상 한도 초과
     */
    429: ErrorResponse;
};

export type UpdateQuestQuestQuestIdPutError = UpdateQuestQuestQuestIdPutErrors[keyof UpdateQuestQuestQuestIdPutErrors];

export type UpdateQuestQuestQuestIdPutResponses = {
    /**
     * 퀘스트 수정 성공
     */
    200: ResponseModelQuestResponse;
};

export type UpdateQuestQuestQuestIdPutResponse = UpdateQuestQuestQuestIdPutResponses[keyof UpdateQuestQuestQuestIdPutResponses];

export type CompleteQuestQuestQuestIdCompletePostData = {
    body?: never;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}/complete';
};

export type CompleteQuestQuestQuestIdCompletePostErrors = {
    /**
     * 퀘스트 완료 불가
     */
    400: ErrorResponse;
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * 퀘스트 반복 한도 초과
     */
    429: ErrorResponse;
};

export type CompleteQuestQuestQuestIdCompletePostError = CompleteQuestQuestQuestIdCompletePostErrors[keyof CompleteQuestQuestQuestIdCompletePostErrors];

export type CompleteQuestQuestQuestIdCompletePostResponses = {
    /**
     * 퀘스트 완료 처리 성공
     */
    200: ResponseModelInt;
};

export type CompleteQuestQuestQuestIdCompletePostResponse = CompleteQuestQuestQuestIdCompletePostResponses[keyof CompleteQuestQuestQuestIdCompletePostResponses];

export type CancelAcceptQuestQuestIdAcceptDeleteData = {
    body?: never;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}/accept';
};

export type CancelAcceptQuestQuestIdAcceptDeleteErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelAcceptQuestQuestIdAcceptDeleteError = CancelAcceptQuestQuestIdAcceptDeleteErrors[keyof CancelAcceptQuestQuestIdAcceptDeleteErrors];

export type CancelAcceptQuestQuestIdAcceptDeleteResponses = {
    /**
     * 수락 취소 성공
     */
    200: ResponseModelNoneType;
};

export type CancelAcceptQuestQuestIdAcceptDeleteResponse = CancelAcceptQuestQuestIdAcceptDeleteResponses[keyof CancelAcceptQuestQuestIdAcceptDeleteResponses];

export type MyAcceptStatusQuestQuestIdAcceptGetData = {
    body?: never;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}/accept';
};

export type MyAcceptStatusQuestQuestIdAcceptGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MyAcceptStatusQuestQuestIdAcceptGetError = MyAcceptStatusQuestQuestIdAcceptGetErrors[keyof MyAcceptStatusQuestQuestIdAcceptGetErrors];

export type MyAcceptStatusQuestQuestIdAcceptGetResponses = {
    /**
     * 현재 유저의 수락 여부 반환
     */
    200: ResponseModelBool;
};

export type MyAcceptStatusQuestQuestIdAcceptGetResponse = MyAcceptStatusQuestQuestIdAcceptGetResponses[keyof MyAcceptStatusQuestQuestIdAcceptGetResponses];

export type AcceptQuestQuestQuestIdAcceptPostData = {
    body?: never;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}/accept';
};

export type AcceptQuestQuestQuestIdAcceptPostErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptQuestQuestQuestIdAcceptPostError = AcceptQuestQuestQuestIdAcceptPostErrors[keyof AcceptQuestQuestQuestIdAcceptPostErrors];

export type AcceptQuestQuestQuestIdAcceptPostResponses = {
    /**
     * 퀘스트 수락 성공
     */
    200: ResponseModelNoneType;
};

export type AcceptQuestQuestQuestIdAcceptPostResponse = AcceptQuestQuestQuestIdAcceptPostResponses[keyof AcceptQuestQuestQuestIdAcceptPostResponses];

export type ListAcceptedStudentsQuestQuestIdAcceptedGetData = {
    body?: never;
    path: {
        /**
         * Quest Id
         */
        quest_id: number;
    };
    query?: never;
    url: '/quest/{quest_id}/accepted';
};

export type ListAcceptedStudentsQuestQuestIdAcceptedGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 퀘스트를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAcceptedStudentsQuestQuestIdAcceptedGetError = ListAcceptedStudentsQuestQuestIdAcceptedGetErrors[keyof ListAcceptedStudentsQuestQuestIdAcceptedGetErrors];

export type ListAcceptedStudentsQuestQuestIdAcceptedGetResponses = {
    /**
     * 수락한 학생 목록 조회 성공
     */
    200: ResponseModelListDict;
};

export type ListAcceptedStudentsQuestQuestIdAcceptedGetResponse = ListAcceptedStudentsQuestQuestIdAcceptedGetResponses[keyof ListAcceptedStudentsQuestQuestIdAcceptedGetResponses];

export type GetPostsPostsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 페이지 번호
         */
        page?: number;
        /**
         * Size
         *
         * 페이지 당 게시글 데이터 갯수 (최대 100)
         */
        size?: number;
    };
    url: '/posts';
};

export type GetPostsPostsGetErrors = {
    /**
     * 인증되지 않은 사용자
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostsPostsGetError = GetPostsPostsGetErrors[keyof GetPostsPostsGetErrors];

export type GetPostsPostsGetResponses = {
    /**
     * 게시글 목록 조회 성공
     */
    200: ResponseModelListPosts;
};

export type GetPostsPostsGetResponse = GetPostsPostsGetResponses[keyof GetPostsPostsGetResponses];

export type CreatePostPostsPostData = {
    body: PostCreateRequest;
    path?: never;
    query?: never;
    url: '/posts';
};

export type CreatePostPostsPostErrors = {
    /**
     * 인증되지 않은 사용자
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePostPostsPostError = CreatePostPostsPostErrors[keyof CreatePostPostsPostErrors];

export type CreatePostPostsPostResponses = {
    /**
     * 게시글 작성 완료
     */
    201: ResponseModelPosts;
};

export type CreatePostPostsPostResponse = CreatePostPostsPostResponses[keyof CreatePostPostsPostResponses];

export type DeletePostPostsPostIdDeleteData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/posts/{post_id}';
};

export type DeletePostPostsPostIdDeleteErrors = {
    /**
     * 인증되지 않은 사용자
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 게시글을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePostPostsPostIdDeleteError = DeletePostPostsPostIdDeleteErrors[keyof DeletePostPostsPostIdDeleteErrors];

export type DeletePostPostsPostIdDeleteResponses = {
    /**
     * 게시글 삭제 완료
     */
    204: void;
};

export type DeletePostPostsPostIdDeleteResponse = DeletePostPostsPostIdDeleteResponses[keyof DeletePostPostsPostIdDeleteResponses];

export type GetPostPostsPostIdGetData = {
    body?: never;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/posts/{post_id}';
};

export type GetPostPostsPostIdGetErrors = {
    /**
     * 인증되지 않은 사용자
     */
    401: ErrorResponse;
    /**
     * 게시글을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPostPostsPostIdGetError = GetPostPostsPostIdGetErrors[keyof GetPostPostsPostIdGetErrors];

export type GetPostPostsPostIdGetResponses = {
    /**
     * 게시글 상세 조회 성공
     */
    200: ResponseModelPosts;
};

export type GetPostPostsPostIdGetResponse = GetPostPostsPostIdGetResponses[keyof GetPostPostsPostIdGetResponses];

export type UpdatePostPostsPostIdPatchData = {
    body: PostUpdateRequest;
    path: {
        /**
         * Post Id
         */
        post_id: number;
    };
    query?: never;
    url: '/posts/{post_id}';
};

export type UpdatePostPostsPostIdPatchErrors = {
    /**
     * 인증되지 않은 사용자
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 게시글을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePostPostsPostIdPatchError = UpdatePostPostsPostIdPatchErrors[keyof UpdatePostPostsPostIdPatchErrors];

export type UpdatePostPostsPostIdPatchResponses = {
    /**
     * 게시글 수정 완료
     */
    200: ResponseModelPosts;
};

export type UpdatePostPostsPostIdPatchResponse = UpdatePostPostsPostIdPatchResponses[keyof UpdatePostPostsPostIdPatchResponses];

export type GetUserStampsStampGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stamp';
};

export type GetUserStampsStampGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
};

export type GetUserStampsStampGetError = GetUserStampsStampGetErrors[keyof GetUserStampsStampGetErrors];

export type GetUserStampsStampGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelListStampsList;
};

export type GetUserStampsStampGetResponse = GetUserStampsStampGetResponses[keyof GetUserStampsStampGetResponses];

export type CreateStampStampPostData = {
    body: StampCreate;
    path?: never;
    query?: never;
    url: '/stamp';
};

export type CreateStampStampPostErrors = {
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * 이미 해당 스탬프를 발급 받음
     */
    409: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStampStampPostError = CreateStampStampPostErrors[keyof CreateStampStampPostErrors];

export type CreateStampStampPostResponses = {
    /**
     * 정상 처리
     */
    204: void;
};

export type CreateStampStampPostResponse = CreateStampStampPostResponses[keyof CreateStampStampPostResponses];
