// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * AdminPointRequest
 */
export const zAdminPointRequest = z.object({
    user_ids: z.array(z.int()),
    amount: z.int(),
    reason: z.string()
});

/**
 * AdminUserUpdateRequest
 */
export const zAdminUserUpdateRequest = z.object({
    name: z.string().nullish(),
    permissions: z.int().nullish()
});

/**
 * ChangePasswordForm
 */
export const zChangePasswordForm = z.object({
    old_password: z.string(),
    new_password: z.string()
});

/**
 * ChangePasswordNewForm
 */
export const zChangePasswordNewForm = z.object({
    user: z.int(),
    password: z.string()
});

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
    success: z.boolean(),
    message: z.string()
});

/**
 * GetLimitResponse
 */
export const zGetLimitResponse = z.object({
    limit: z.int(),
    target_limit: z.int()
});

/**
 * KaraokeBidCreate
 */
export const zKaraokeBidCreate = z.object({
    amount: z.int().gt(0)
});

/**
 * KaraokeBids
 */
export const zKaraokeBids = z.object({
    id: z.int().nullish(),
    auction_id: z.int(),
    bidder_id: z.int(),
    party_id: z.int().nullable(),
    amount: z.int(),
    created_at: z.iso.datetime({ offset: true }).optional()
});

/**
 * KaraokeCreate
 */
export const zKaraokeCreate = z.object({
    date: z.iso.date(),
    time: z.int().gte(1).lte(8),
    start_time: z.iso.datetime({ offset: true }),
    end_time: z.iso.datetime({ offset: true }),
    min_point: z.int().optional().default(0)
});

/**
 * KaraokeInviteAction
 */
export const zKaraokeInviteAction = z.object({
    accept: z.boolean()
});

/**
 * KaraokeInviteCreate
 */
export const zKaraokeInviteCreate = z.object({
    user_id: z.int()
});

/**
 * KaraokeMembers
 */
export const zKaraokeMembers = z.object({
    party_id: z.int(),
    user_id: z.int(),
    pending: z.boolean().optional().default(true)
});

/**
 * KaraokePartis
 */
export const zKaraokePartis = z.object({
    id: z.int().nullish(),
    auction_id: z.int(),
    leader_id: z.int(),
    dispersed: z.boolean().optional().default(false)
});

/**
 * KaraokeStatus
 */
export const zKaraokeStatus = z.enum([
    'Pending',
    'In_Progress',
    'Confirmed'
]);

/**
 * KaraokeResponse
 */
export const zKaraokeResponse = z.object({
    id: z.int().nullish(),
    date: z.iso.date(),
    time: z.int(),
    status: zKaraokeStatus.optional().default('Pending'),
    start_time: z.iso.datetime({ offset: true }),
    end_time: z.iso.datetime({ offset: true }),
    min_point: z.int().optional().default(0),
    highest_bid: z.int().nullish()
});

/**
 * Karaokes
 */
export const zKaraokes = z.object({
    id: z.int().nullish(),
    date: z.iso.date(),
    time: z.int(),
    status: zKaraokeStatus.optional().default('Pending'),
    start_time: z.iso.datetime({ offset: true }),
    end_time: z.iso.datetime({ offset: true }),
    min_point: z.int().optional().default(0)
});

/**
 * LoginForm
 */
export const zLoginForm = z.object({
    id: z.int(),
    password: z.string()
});

/**
 * PointHistoryType
 */
export const zPointHistoryType = z.enum([
    'teacher',
    'cafe',
    'food',
    'etc',
    'grant',
    'quest',
    'stamp',
    'stamp_bonus',
    'karaoke_bid',
    'karaoke_cancel'
]);

/**
 * PointHistory
 */
export const zPointHistory = z.object({
    id: z.int().nullish(),
    user_id: z.int(),
    changed_amount: z.int(),
    reason: z.string(),
    memo: z.string().nullish(),
    type: zPointHistoryType.nullish(),
    created_at: z.iso.datetime({ offset: true }).optional()
});

/**
 * PointOperation
 */
export const zPointOperation = z.object({
    target_user_id: z.int(),
    amount: z.int().gt(0),
    change_type: zPointHistoryType.nullish(),
    memo: z.string().nullish()
});

/**
 * PostCreateRequest
 */
export const zPostCreateRequest = z.object({
    title: z.string(),
    content_data: z.record(z.string(), z.unknown())
});

/**
 * PostUpdateRequest
 */
export const zPostUpdateRequest = z.object({
    title: z.string().nullish(),
    content_data: z.record(z.string(), z.unknown()).nullish()
});

/**
 * Posts
 */
export const zPosts = z.object({
    id: z.int().nullish(),
    title: z.string(),
    views: z.int().optional().default(0),
    created_at: z.iso.datetime({ offset: true }).optional(),
    updated_at: z.iso.datetime({ offset: true }).optional(),
    author_id: z.int()
});

/**
 * QuestOperation
 */
export const zQuestOperation = z.object({
    title: z.string(),
    description: z.string(),
    reward: z.int().gt(0),
    end_date: z.iso.datetime({ offset: true }),
    max_repeat: z.int().gte(1)
});

/**
 * QuestUpdate
 */
export const zQuestUpdate = z.object({
    title: z.string().nullish(),
    description: z.string().nullish(),
    reward: z.int().gt(0).nullish(),
    end_date: z.iso.datetime({ offset: true }).nullish(),
    max_repeat: z.int().gte(1).nullish()
});

/**
 * Quests
 */
export const zQuests = z.object({
    id: z.int().nullish(),
    title: z.string(),
    description: z.string(),
    reward: z.int(),
    end_date: z.iso.datetime({ offset: true }),
    max_repeat: z.int().optional().default(1),
    created_at: z.iso.datetime({ offset: true }).optional(),
    author_id: z.int()
});

/**
 * RankingResponse
 */
export const zRankingResponse = z.object({
    id: z.int(),
    name: z.string(),
    grade: z.int().nullable(),
    number: z.int().nullable(),
    total_point: z.int(),
    rank: z.int()
});

/**
 * ResponseModel[GetLimitResponse]
 */
export const zResponseModelGetLimitResponse = z.object({
    success: z.boolean(),
    data: zGetLimitResponse
});

/**
 * ResponseModel[KaraokeBids]
 */
export const zResponseModelKaraokeBids = z.object({
    success: z.boolean(),
    data: zKaraokeBids
});

/**
 * ResponseModel[KaraokePartis]
 */
export const zResponseModelKaraokePartis = z.object({
    success: z.boolean(),
    data: zKaraokePartis
});

/**
 * ResponseModel[KaraokeResponse]
 */
export const zResponseModelKaraokeResponse = z.object({
    success: z.boolean(),
    data: zKaraokeResponse
});

/**
 * ResponseModel[Karaokes]
 */
export const zResponseModelKaraokes = z.object({
    success: z.boolean(),
    data: zKaraokes
});

/**
 * ResponseModel[PointHistory]
 */
export const zResponseModelPointHistory = z.object({
    success: z.boolean(),
    data: zPointHistory
});

/**
 * ResponseModel[Posts]
 */
export const zResponseModelPosts = z.object({
    success: z.boolean(),
    data: zPosts
});

/**
 * ResponseModel[Quests]
 */
export const zResponseModelQuests = z.object({
    success: z.boolean(),
    data: zQuests
});

/**
 * ResponseModel[bool]
 */
export const zResponseModelBool = z.object({
    success: z.boolean(),
    data: z.boolean()
});

/**
 * ResponseModel[int]
 */
export const zResponseModelInt = z.object({
    success: z.boolean(),
    data: z.int()
});

/**
 * ResponseModel[list[KaraokeMembers]]
 */
export const zResponseModelListKaraokeMembers = z.object({
    success: z.boolean(),
    data: z.array(zKaraokeMembers)
});

/**
 * ResponseModel[list[KaraokeResponse]]
 */
export const zResponseModelListKaraokeResponse = z.object({
    success: z.boolean(),
    data: z.array(zKaraokeResponse)
});

/**
 * ResponseModel[list[PointHistory]]
 */
export const zResponseModelListPointHistory = z.object({
    success: z.boolean(),
    data: z.array(zPointHistory)
});

/**
 * ResponseModel[list[Posts]]
 */
export const zResponseModelListPosts = z.object({
    success: z.boolean(),
    data: z.array(zPosts)
});

/**
 * ResponseModel[list[Quests]]
 */
export const zResponseModelListQuests = z.object({
    success: z.boolean(),
    data: z.array(zQuests)
});

/**
 * ResponseModel[list[RankingResponse]]
 */
export const zResponseModelListRankingResponse = z.object({
    success: z.boolean(),
    data: z.array(zRankingResponse)
});

/**
 * StampType
 *
 * 스탬프 종류 Enum
 * - 부스 이름은 추후 수정될 수 있습니다.
 */
export const zStampType = z.enum([
    '쓰레기 투호',
    '철권 한판',
    '큐피트의 다트',
    '제기찰겨? 날찰겨?',
    '팔씨름 최강자전',
    '부적꾸미기',
    '누르기 챌린지',
    '공놀이 괴물',
    '철면피 노래방',
    '절대음감',
    '런닝맨',
    '의자뺏기',
    '단체줄넘기',
    '수학 키캡'
]);

/**
 * StampCreate
 */
export const zStampCreate = z.object({
    user_id: z.int(),
    stamp_type: zStampType
});

/**
 * StampsList
 */
export const zStampsList = z.object({
    stamp: z.string(),
    name: z.string(),
    have: z.boolean(),
    time: z.iso.datetime({ offset: true }).nullable()
});

/**
 * ResponseModel[list[StampsList]]
 */
export const zResponseModelListStampsList = z.object({
    success: z.boolean(),
    data: z.array(zStampsList)
});

/**
 * UserPermission
 *
 * 유저 권한 IntFlag.
 * 작명시 `동사_목적`으로 작성하며, 대문자로만 작성한다.
 * 예) 포인트 관리 -> MANAGE_POINT
 */
export const zUserPermission = z.union([
    z.literal(0),
    z.literal(131072),
    z.literal(1),
    z.literal(131073),
    z.literal(2),
    z.literal(131074),
    z.literal(4),
    z.literal(8),
    z.literal(16),
    z.literal(32),
    z.literal(131104),
    z.literal(64),
    z.literal(128),
    z.literal(256),
    z.literal(512),
    z.literal(1024),
    z.literal(2048),
    z.literal(133120),
    z.literal(4096),
    z.literal(8192),
    z.literal(139264),
    z.literal(16384),
    z.literal(32768),
    z.literal(65536),
    z.literal(262144),
    z.literal(524288),
    z.literal(1048576),
    z.literal(1561024),
    z.literal(182730),
    z.literal(665104)
]);

/**
 * UserType
 */
export const zUserType = z.enum([
    'student',
    'teacher',
    'service'
]);

/**
 * AdminUserCreateRequest
 */
export const zAdminUserCreateRequest = z.object({
    name: z.string(),
    user_type: zUserType,
    grade: z.int().nullish(),
    number: z.int().nullish(),
    student_no: z.int().nullish()
});

/**
 * User
 */
export const zUser = z.object({
    id: z.int().nullish(),
    type: zUserType,
    name: z.string(),
    grade: z.int().nullable(),
    number: z.int().nullable(),
    point: z.int().optional().default(0),
    total_point: z.int().optional().default(0),
    permissions: z.int().optional().default(0),
    history_type: zPointHistoryType.nullish()
});

/**
 * KaraokeFinalBidResponse
 */
export const zKaraokeFinalBidResponse = z.object({
    id: z.int(),
    auction_id: z.int(),
    party_id: z.int().nullable(),
    amount: z.int(),
    created_at: z.iso.datetime({ offset: true }),
    bidder: zUser
});

/**
 * KaraokePartyDetail
 */
export const zKaraokePartyDetail = z.object({
    id: z.int(),
    auction_id: z.int(),
    leader_id: z.int(),
    dispersed: z.boolean(),
    leader: zUser,
    members: z.array(zUser),
    pending_members: z.array(zUser)
});

/**
 * ResponseModel[KaraokeFinalBidResponse]
 */
export const zResponseModelKaraokeFinalBidResponse = z.object({
    success: z.boolean(),
    data: zKaraokeFinalBidResponse
});

/**
 * ResponseModel[KaraokePartyDetail]
 */
export const zResponseModelKaraokePartyDetail = z.object({
    success: z.boolean(),
    data: zKaraokePartyDetail
});

/**
 * ResponseModel[User]
 */
export const zResponseModelUser = z.object({
    success: z.boolean(),
    data: zUser
});

/**
 * ResponseModel[list[User]]
 */
export const zResponseModelListUser = z.object({
    success: z.boolean(),
    data: z.array(zUser)
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zReadRootGetQuery = z.object({
    _: zUserPermission.nullish()
});

export const zLoginAuthLoginPostBody = zLoginForm;

/**
 * 정상적으로 로그인이 되었음
 */
export const zLoginAuthLoginPostResponse = zResponseModelUser;

/**
 * 정상적으로 로그아웃이 되었음
 */
export const zLogoutAuthLogoutPostResponse = z.void();

/**
 * 세션이 정상적으로 유효함
 */
export const zGetCurrentUserAuthGetResponse = zResponseModelUser;

export const zChangePasswordNewAuthPasswordPostBody = zChangePasswordNewForm;

/**
 * 비밀번호 변경 성공
 */
export const zChangePasswordNewAuthPasswordPostResponse = z.void();

export const zChangePasswordAuthPasswordPutBody = zChangePasswordForm;

/**
 * 비밀번호 변경 성공
 */
export const zChangePasswordAuthPasswordPutResponse = z.void();

export const zCheckPasswordExistsAuthPasswordExistsUserIdGetPath = z.object({
    user_id: z.int()
});

export const zCheckPasswordExistsAuthPasswordExistsUserIdGetQuery = z.object({
    t: zUserType.nullish()
});

/**
 * 정상 조회
 */
export const zCheckPasswordExistsAuthPasswordExistsUserIdGetResponse = zResponseModelBool;

export const zGetLimitPointLimitTargetUserIdGetPath = z.object({
    target_user_id: z.int()
});

/**
 * 정상적으로 처리됨
 */
export const zGetLimitPointLimitTargetUserIdGetResponse = zResponseModelGetLimitResponse;

/**
 * 정상적으로 처리됨
 */
export const zGetLimitSessionPointLimitGetResponse = zResponseModelInt;

export const zGrantPointsPointGrantPostBody = zPointOperation;

/**
 * 정상적으로 지급이 되었음
 */
export const zGrantPointsPointGrantPostResponse = z.void();

export const zDeductPointsPointDeductPostBody = zPointOperation;

export const zDeductPointsPointDeductPostResponse = z.union([
    zResponseModelInt,
    z.void()
]);

export const zGetHistoryListPointHistoryGetQuery = z.object({
    limit: z.int().optional().default(20),
    offset: z.int().optional().default(0)
});

/**
 * 정상처리
 */
export const zGetHistoryListPointHistoryGetResponse = zResponseModelListPointHistory;

export const zGetHistoryPointHistoryTargetIdGetPath = z.object({
    target_id: z.int()
});

/**
 * 정상처리
 */
export const zGetHistoryPointHistoryTargetIdGetResponse = zResponseModelPointHistory;

export const zGetStudentRankingPointRankingStudentGetQuery = z.object({
    limit: z.int().optional().default(20),
    offset: z.int().optional().default(0)
});

/**
 * 정상 처리
 */
export const zGetStudentRankingPointRankingStudentGetResponse = zResponseModelListRankingResponse;

export const zGetTeacherRankingPointRankingTeacherGetQuery = z.object({
    limit: z.int().optional().default(20),
    offset: z.int().optional().default(0)
});

/**
 * 정상 처리
 */
export const zGetTeacherRankingPointRankingTeacherGetResponse = zResponseModelListRankingResponse;

export const zGetPointBalancePointTargetUserIdGetPath = z.object({
    target_user_id: z.int()
});

/**
 * 정상 처리
 */
export const zGetPointBalancePointTargetUserIdGetResponse = zResponseModelInt;

export const zSearchSearchGetQuery = z.object({
    q: z.string(),
    t: z.array(zUserType).nullish()
});

/**
 * 정상 처리
 */
export const zSearchSearchGetResponse = zResponseModelListUser;

export const zTeacherGetByNameSearchTeacherUserNameGetPath = z.object({
    user_name: z.string()
});

/**
 * 정상 처리
 */
export const zTeacherGetByNameSearchTeacherUserNameGetResponse = zResponseModelUser;

export const zGetUsersAdminUsersGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    size: z.int().gte(1).lte(100).optional().default(20),
    user_type: zUserType.nullish(),
    permission: z.int().nullish()
});

/**
 * 정상적으로 처리 됨
 */
export const zGetUsersAdminUsersGetResponse = zResponseModelListUser;

export const zUpdateUsersPointAdminPointPostBody = zAdminPointRequest;

/**
 * 정상 처리
 */
export const zUpdateUsersPointAdminPointPostResponse = z.void();

export const zCreateUserAdminUserPostBody = zAdminUserCreateRequest;

/**
 * 사용자 생성 완료
 */
export const zCreateUserAdminUserPostResponse = zResponseModelUser;

export const zResetUserPasswordAdminUsersUserIdPasswordPatchPath = z.object({
    user_id: z.int()
});

/**
 * 정상 처리 (비밀번호 초기화됨)
 */
export const zResetUserPasswordAdminUsersUserIdPasswordPatchResponse = z.void();

export const zDeleteUserAdminUsersUserIdDeletePath = z.object({
    user_id: z.int()
});

/**
 * 정상 처리
 */
export const zDeleteUserAdminUsersUserIdDeleteResponse = z.void();

export const zUpdateUserAdminUsersUserIdPatchBody = zAdminUserUpdateRequest;

export const zUpdateUserAdminUsersUserIdPatchPath = z.object({
    user_id: z.int()
});

/**
 * 사용자 정보 수정 완료
 */
export const zUpdateUserAdminUsersUserIdPatchResponse = zResponseModelUser;

export const zCreateQuestQuestCreatePostBody = zQuestOperation;

/**
 * 퀘스트 생성 성공
 */
export const zCreateQuestQuestCreatePostResponse = zResponseModelQuests;

export const zListQuestsQuestGetQuery = z.object({
    limit: z.int().optional().default(20),
    offset: z.int().optional().default(0)
});

/**
 * 퀘스트 목록 조회 성공
 */
export const zListQuestsQuestGetResponse = zResponseModelListQuests;

export const zDeleteQuestQuestQuestIdDeletePath = z.object({
    quest_id: z.int()
});

/**
 * 퀘스트 삭제 성공
 */
export const zDeleteQuestQuestQuestIdDeleteResponse = z.void();

export const zGetQuestQuestQuestIdGetPath = z.object({
    quest_id: z.int()
});

/**
 * 퀘스트 조회 성공
 */
export const zGetQuestQuestQuestIdGetResponse = zResponseModelQuests;

export const zUpdateQuestQuestQuestIdPutBody = zQuestUpdate;

export const zUpdateQuestQuestQuestIdPutPath = z.object({
    quest_id: z.int()
});

/**
 * 퀘스트 수정 성공
 */
export const zUpdateQuestQuestQuestIdPutResponse = zResponseModelQuests;

export const zCompleteQuestQuestQuestIdCompletePostPath = z.object({
    quest_id: z.int()
});

/**
 * 퀘스트 완료 처리 성공
 */
export const zCompleteQuestQuestQuestIdCompletePostResponse = zResponseModelInt;

export const zGetPostsPostsGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    size: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * 게시글 목록 조회 성공
 */
export const zGetPostsPostsGetResponse = zResponseModelListPosts;

export const zCreatePostPostsPostBody = zPostCreateRequest;

/**
 * 게시글 작성 완료
 */
export const zCreatePostPostsPostResponse = zResponseModelPosts;

export const zDeletePostPostsPostIdDeletePath = z.object({
    post_id: z.int()
});

/**
 * 게시글 삭제 완료
 */
export const zDeletePostPostsPostIdDeleteResponse = z.void();

export const zGetPostPostsPostIdGetPath = z.object({
    post_id: z.int()
});

/**
 * 게시글 상세 조회 성공
 */
export const zGetPostPostsPostIdGetResponse = zResponseModelPosts;

export const zUpdatePostPostsPostIdPatchBody = zPostUpdateRequest;

export const zUpdatePostPostsPostIdPatchPath = z.object({
    post_id: z.int()
});

/**
 * 게시글 수정 완료
 */
export const zUpdatePostPostsPostIdPatchResponse = zResponseModelPosts;

/**
 * 정상 처리
 */
export const zGetUserStampsStampGetResponse = zResponseModelListStampsList;

export const zCreateStampStampPostBody = zStampCreate;

/**
 * 정상 처리
 */
export const zCreateStampStampPostResponse = z.void();

export const zGetKaraokeListQuery = z.object({
    date: z.iso.date().nullish()
});

/**
 * 정상적으로 처리됨.
 */
export const zGetKaraokeListResponse = zResponseModelListKaraokeResponse;

export const zCreateKaraokeBody = zKaraokeCreate;

/**
 * 정상적으로 생성이 완료됨
 */
export const zCreateKaraokeResponse = zResponseModelKaraokes;

export const zDeleteKaraokePath = z.object({
    karaoke_id: z.int()
});

/**
 * 정상적으로 처리됨.
 */
export const zDeleteKaraokeResponse = z.void();

export const zGetKaraokePath = z.object({
    karaoke_id: z.int()
});

/**
 * 정상적으로 처리됨.
 */
export const zGetKaraokeResponse = zResponseModelKaraokeResponse;

export const zCreateKaraokePartyPath = z.object({
    karaoke_id: z.int()
});

/**
 * 정상적으로 파티 생성 완료
 */
export const zCreateKaraokePartyResponse = zResponseModelKaraokePartis;

export const zGetMyKaraokePartyPath = z.object({
    karaoke_id: z.int()
});

/**
 * 정상적으로 처리됨.
 */
export const zGetMyKaraokePartyResponse = zResponseModelKaraokePartyDetail;

export const zCreateKaraokeBidBody = zKaraokeBidCreate;

export const zCreateKaraokeBidPath = z.object({
    karaoke_id: z.int()
});

/**
 * 정상적으로 입찰 완료
 */
export const zCreateKaraokeBidResponse = zResponseModelKaraokeBids;

export const zGetKaraokeFinalBidPath = z.object({
    karaoke_id: z.int()
});

/**
 * 정상적으로 처리됨.
 */
export const zGetKaraokeFinalBidResponse = zResponseModelKaraokeFinalBidResponse;

export const zDisperseKaraokePartyPath = z.object({
    party_id: z.int()
});

/**
 * 정상적으로 파티 해산 완료
 */
export const zDisperseKaraokePartyResponse = z.void();

export const zGetKaraokePartyPath = z.object({
    party_id: z.int()
});

/**
 * 정상적으로 처리됨.
 */
export const zGetKaraokePartyResponse = zResponseModelKaraokePartyDetail;

export const zLeaveKaraokePartyPath = z.object({
    party_id: z.int()
});

/**
 * 정상적으로 파티 탈퇴 완료
 */
export const zLeaveKaraokePartyResponse = z.void();

export const zKickKaraokePartyMemberPath = z.object({
    party_id: z.int(),
    user_id: z.int()
});

/**
 * 정상적으로 멤버 강퇴 완료
 */
export const zKickKaraokePartyMemberResponse = zResponseModelKaraokePartyDetail;

export const zInviteKaraokePartyMemberBody = zKaraokeInviteCreate;

export const zInviteKaraokePartyMemberPath = z.object({
    party_id: z.int()
});

/**
 * 정상적으로 초대 완료
 */
export const zInviteKaraokePartyMemberResponse = z.void();

/**
 * Successful Response
 */
export const zGetMyKaraokePartyInvitesResponse = zResponseModelListKaraokeMembers;

export const zDecideKaraokePartyInviteBody = zKaraokeInviteAction;

export const zDecideKaraokePartyInvitePath = z.object({
    party_id: z.int()
});

/**
 * 정상적으로 수락/거절 완료
 */
export const zDecideKaraokePartyInviteResponse = zResponseModelBool;
