// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ChangePasswordAuthPasswordPutData, ChangePasswordAuthPasswordPutErrors, ChangePasswordAuthPasswordPutResponses, ChangePasswordNewAuthPasswordPostData, ChangePasswordNewAuthPasswordPostErrors, ChangePasswordNewAuthPasswordPostResponses, CheckPasswordExistsAuthPasswordExistsUserIdGetData, CheckPasswordExistsAuthPasswordExistsUserIdGetErrors, CheckPasswordExistsAuthPasswordExistsUserIdGetResponses, DeductPointsPointDeductPostData, DeductPointsPointDeductPostErrors, DeductPointsPointDeductPostResponses, GetCurrentUserAuthGetData, GetCurrentUserAuthGetErrors, GetCurrentUserAuthGetResponses, GetPointBalancePointTargetUserIdGetData, GetPointBalancePointTargetUserIdGetErrors, GetPointBalancePointTargetUserIdGetResponses, GrantPointsPointGrantPostData, GrantPointsPointGrantPostErrors, GrantPointsPointGrantPostResponses, LoginAuthLoginPostData, LoginAuthLoginPostErrors, LoginAuthLoginPostResponses, LogoutAuthLogoutPostData, LogoutAuthLogoutPostResponses, PointHistoryPointHistoryGetData, PointHistoryPointHistoryGetErrors, PointHistoryPointHistoryGetResponses, ReadRootGetData, ReadRootGetResponses, SearchStudentSearchStudentGetData, SearchStudentSearchStudentGetErrors, SearchStudentSearchStudentGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>) => (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * 로그인
 *
 * ID와 비밀번호를 통해 로그인을 진행합니다. 로그인을 성공한 경우 해당 유저의 정보를 응답합니다.
 */
export const loginAuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginAuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginAuthLoginPostResponses, LoginAuthLoginPostErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 로그아웃
 *
 * 현재 로그인된 세션을 종료합니다.
 */
export const logoutAuthLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<LogoutAuthLogoutPostData, ThrowOnError>) => (options?.client ?? client).post<LogoutAuthLogoutPostResponses, unknown, ThrowOnError>({ url: '/auth/logout', ...options });

/**
 * 인증
 *
 * 현재 로그인된 유저의 정보를 반환합니다.
 */
export const getCurrentUserAuthGet = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserAuthGetData, ThrowOnError>) => (options?.client ?? client).get<GetCurrentUserAuthGetResponses, GetCurrentUserAuthGetErrors, ThrowOnError>({ url: '/auth', ...options });

/**
 * 비밀번호 초기 변경
 *
 * 첫 로그인시 비밀번호 변경을 합니다.
 */
export const changePasswordNewAuthPasswordPost = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordNewAuthPasswordPostData, ThrowOnError>) => (options.client ?? client).post<ChangePasswordNewAuthPasswordPostResponses, ChangePasswordNewAuthPasswordPostErrors, ThrowOnError>({
    url: '/auth/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 비밀번호 변경
 *
 * 로그인된 유저의 비밀번호를 변경합니다.
 */
export const changePasswordAuthPasswordPut = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordAuthPasswordPutData, ThrowOnError>) => (options.client ?? client).put<ChangePasswordAuthPasswordPutResponses, ChangePasswordAuthPasswordPutErrors, ThrowOnError>({
    url: '/auth/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 비밀번호 존재 여부 확인
 *
 * 특정 ID의 유저가 비밀번호를 가지고 있는지(None이 아닌지) 여부를 확인합니다.
 */
export const checkPasswordExistsAuthPasswordExistsUserIdGet = <ThrowOnError extends boolean = false>(options: Options<CheckPasswordExistsAuthPasswordExistsUserIdGetData, ThrowOnError>) => (options.client ?? client).get<CheckPasswordExistsAuthPasswordExistsUserIdGetResponses, CheckPasswordExistsAuthPasswordExistsUserIdGetErrors, ThrowOnError>({ url: '/auth/password/exists/{user_id}', ...options });

/**
 * 포인트 지급
 *
 * 특정 유저에게 포인트를 지급합니다. (교사 전용)
 */
export const grantPointsPointGrantPost = <ThrowOnError extends boolean = false>(options: Options<GrantPointsPointGrantPostData, ThrowOnError>) => (options.client ?? client).post<GrantPointsPointGrantPostResponses, GrantPointsPointGrantPostErrors, ThrowOnError>({
    url: '/point/grant',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 포인트 차감
 *
 * 특정 유저의 포인트를 차감합니다. (서비스 유저 전용)
 */
export const deductPointsPointDeductPost = <ThrowOnError extends boolean = false>(options: Options<DeductPointsPointDeductPostData, ThrowOnError>) => (options.client ?? client).post<DeductPointsPointDeductPostResponses, DeductPointsPointDeductPostErrors, ThrowOnError>({
    url: '/point/deduct',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * 포인트 조회
 *
 * 특정 유저의 현재 포인트를 조회합니다.
 */
export const getPointBalancePointTargetUserIdGet = <ThrowOnError extends boolean = false>(options: Options<GetPointBalancePointTargetUserIdGetData, ThrowOnError>) => (options.client ?? client).get<GetPointBalancePointTargetUserIdGetResponses, GetPointBalancePointTargetUserIdGetErrors, ThrowOnError>({ url: '/point/{target_user_id}', ...options });

/**
 * 포인트 기록
 *
 * 현재 로그인한 자기자신의 포인트 기록을 조회합니다.
 */
export const pointHistoryPointHistoryGet = <ThrowOnError extends boolean = false>(options?: Options<PointHistoryPointHistoryGetData, ThrowOnError>) => (options?.client ?? client).get<PointHistoryPointHistoryGetResponses, PointHistoryPointHistoryGetErrors, ThrowOnError>({ url: '/point/history', ...options });

/**
 * 학생 검색
 *
 * 학생 유저를 이름 또는 ID(학번)으로 검색합니다.
 */
export const searchStudentSearchStudentGet = <ThrowOnError extends boolean = false>(options: Options<SearchStudentSearchStudentGetData, ThrowOnError>) => (options.client ?? client).get<SearchStudentSearchStudentGetResponses, SearchStudentSearchStudentGetErrors, ThrowOnError>({ url: '/search/student', ...options });
