// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ChangePasswordForm
 */
export type ChangePasswordForm = {
    /**
     * Old Password
     */
    old_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     *
     * 에러 메시지
     */
    message: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginForm
 */
export type LoginForm = {
    /**
     * Id
     */
    id: number;
    /**
     * Password
     */
    password: string;
};

/**
 * PointHistory
 */
export type PointHistory = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Changed Amount
     *
     * 변경된 포인트의 정도
     */
    changed_amount: number;
    /**
     * Reason
     *
     * 이유
     */
    reason: string;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * PointOperation
 */
export type PointOperation = {
    /**
     * Target User Id
     */
    target_user_id: number;
    /**
     * Amount
     *
     * Amount of points
     */
    amount: number;
};

/**
 * ResponseModel[List[User]]
 */
export type ResponseModelListUser = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<User>;
};

/**
 * ResponseModel[User]
 */
export type ResponseModelUser = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: User;
};

/**
 * ResponseModel[bool]
 */
export type ResponseModelBool = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: boolean;
};

/**
 * ResponseModel[int]
 */
export type ResponseModelInt = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: number;
};

/**
 * ResponseModel[list[PointHistory]]
 */
export type ResponseModelListPointHistory = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<PointHistory>;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     *
     * 고유 ID. 교사, 서비스의 경우 자동생성. 학생의 경우 학번 사용
     */
    id?: number | null;
    /**
     * 유저 종류 (학생, 교사, 서비스)
     */
    type: UserType;
    /**
     * Name
     *
     * 이름
     */
    name: string;
    /**
     * Grade
     *
     * 학년
     */
    grade: number | null;
    /**
     * Number
     *
     * 반
     */
    number: number | null;
    /**
     * Point
     *
     * 보유 포인트
     */
    point?: number;
};

/**
 * UserType
 */
export type UserType = 'student' | 'teacher' | 'service';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginAuthLoginPostData = {
    body: LoginForm;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * ID 또는 비밀번호가 일치하지 않습니다.
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * 정상적으로 로그인이 되었음
     */
    200: ResponseModelUser;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * 정상적으로 로그아웃이 되었음
     */
    204: void;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type GetCurrentUserAuthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth';
};

export type GetCurrentUserAuthGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음.
     */
    401: ErrorResponse;
};

export type GetCurrentUserAuthGetError = GetCurrentUserAuthGetErrors[keyof GetCurrentUserAuthGetErrors];

export type GetCurrentUserAuthGetResponses = {
    /**
     * 세션이 정상적으로 유효함
     */
    200: ResponseModelUser;
};

export type GetCurrentUserAuthGetResponse = GetCurrentUserAuthGetResponses[keyof GetCurrentUserAuthGetResponses];

export type ChangePasswordAuthPasswordPutData = {
    body: ChangePasswordForm;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type ChangePasswordAuthPasswordPutErrors = {
    /**
     * 기존 비밀번호가 일치하지 않음
     */
    400: ErrorResponse;
    /**
     * 세션이 만료되었거나 유효하지 않음.
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordAuthPasswordPutError = ChangePasswordAuthPasswordPutErrors[keyof ChangePasswordAuthPasswordPutErrors];

export type ChangePasswordAuthPasswordPutResponses = {
    /**
     * 비밀번호 변경 성공
     */
    204: void;
};

export type ChangePasswordAuthPasswordPutResponse = ChangePasswordAuthPasswordPutResponses[keyof ChangePasswordAuthPasswordPutResponses];

export type CheckPasswordExistsAuthPasswordExistsUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/auth/password/exists/{user_id}';
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetErrors = {
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetError = CheckPasswordExistsAuthPasswordExistsUserIdGetErrors[keyof CheckPasswordExistsAuthPasswordExistsUserIdGetErrors];

export type CheckPasswordExistsAuthPasswordExistsUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelBool;
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetResponse = CheckPasswordExistsAuthPasswordExistsUserIdGetResponses[keyof CheckPasswordExistsAuthPasswordExistsUserIdGetResponses];

export type GrantPointsPointGrantPostData = {
    body: PointOperation;
    path?: never;
    query?: never;
    url: '/point/grant';
};

export type GrantPointsPointGrantPostErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 지급할 학생을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GrantPointsPointGrantPostError = GrantPointsPointGrantPostErrors[keyof GrantPointsPointGrantPostErrors];

export type GrantPointsPointGrantPostResponses = {
    /**
     * 정상적으로 지급이 되었음
     */
    204: void;
};

export type GrantPointsPointGrantPostResponse = GrantPointsPointGrantPostResponses[keyof GrantPointsPointGrantPostResponses];

export type DeductPointsPointDeductPostData = {
    body: PointOperation;
    path?: never;
    query?: never;
    url: '/point/deduct';
};

export type DeductPointsPointDeductPostErrors = {
    /**
     * 포인트 부족
     */
    400: ErrorResponse;
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 차감할 학생을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeductPointsPointDeductPostError = DeductPointsPointDeductPostErrors[keyof DeductPointsPointDeductPostErrors];

export type DeductPointsPointDeductPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInt;
    /**
     * 정상적으로 차감이 되었음
     */
    204: void;
};

export type DeductPointsPointDeductPostResponse = DeductPointsPointDeductPostResponses[keyof DeductPointsPointDeductPostResponses];

export type GetPointBalancePointTargetUserIdGetData = {
    body?: never;
    path: {
        /**
         * Target User Id
         */
        target_user_id: number;
    };
    query?: never;
    url: '/point/{target_user_id}';
};

export type GetPointBalancePointTargetUserIdGetErrors = {
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPointBalancePointTargetUserIdGetError = GetPointBalancePointTargetUserIdGetErrors[keyof GetPointBalancePointTargetUserIdGetErrors];

export type GetPointBalancePointTargetUserIdGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelInt;
};

export type GetPointBalancePointTargetUserIdGetResponse = GetPointBalancePointTargetUserIdGetResponses[keyof GetPointBalancePointTargetUserIdGetResponses];

export type PointHistoryPointHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/point/history';
};

export type PointHistoryPointHistoryGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PointHistoryPointHistoryGetError = PointHistoryPointHistoryGetErrors[keyof PointHistoryPointHistoryGetErrors];

export type PointHistoryPointHistoryGetResponses = {
    /**
     * 정상처리
     */
    200: ResponseModelListPointHistory;
};

export type PointHistoryPointHistoryGetResponse = PointHistoryPointHistoryGetResponses[keyof PointHistoryPointHistoryGetResponses];

export type SearchStudentSearchStudentGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
    };
    url: '/search/student';
};

export type SearchStudentSearchStudentGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchStudentSearchStudentGetError = SearchStudentSearchStudentGetErrors[keyof SearchStudentSearchStudentGetErrors];

export type SearchStudentSearchStudentGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelListUser;
};

export type SearchStudentSearchStudentGetResponse = SearchStudentSearchStudentGetResponses[keyof SearchStudentSearchStudentGetResponses];
