// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AdminPointRequest
 */
export type AdminPointRequest = {
    /**
     * User Ids
     *
     * 포인트를 지급/차감할 학생 ID 목록. 전체 학생 대상일 경우 생략하거나 null/빈 리스트 전달
     */
    user_ids?: Array<number> | null;
    /**
     * Amount
     *
     * 변동될 포인트 (양수는 지급, 음수는 차감)
     */
    amount: number;
    /**
     * Reason
     *
     * 포인트 변동 사유
     */
    reason: string;
    /**
     * Is All Students
     *
     * 전체 학생 대상 여부. true일 경우 user_ids는 무시됩니다.
     */
    is_all_students?: boolean;
};

/**
 * ChangePasswordForm
 */
export type ChangePasswordForm = {
    /**
     * Old Password
     */
    old_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ChangePasswordNewForm
 */
export type ChangePasswordNewForm = {
    /**
     * User
     */
    user: number;
    /**
     * Password
     */
    password: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     *
     * 에러 메시지
     */
    message: string;
};

/**
 * GetLimitResponse
 */
export type GetLimitResponse = {
    /**
     * Limit
     */
    limit: number;
    /**
     * Target Limit
     */
    target_limit: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginForm
 */
export type LoginForm = {
    /**
     * Id
     */
    id: number;
    /**
     * Password
     */
    password: string;
};

/**
 * PointHistory
 */
export type PointHistory = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * User Id
     */
    user_id: number;
    /**
     * Changed Amount
     *
     * 변경된 포인트의 정도
     */
    changed_amount: number;
    /**
     * Reason
     *
     * 이유
     */
    reason: string;
    /**
     * 기록 종류
     */
    type?: PointHistoryType | null;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * PointHistoryType
 */
export type PointHistoryType = 'teacher' | 'cafe' | 'food' | 'etc' | 'grant';

/**
 * PointOperation
 */
export type PointOperation = {
    /**
     * Target User Id
     */
    target_user_id: number;
    /**
     * Amount
     *
     * 처리할 포인트
     */
    amount: number;
    /**
     * 포인트를 처리하는 이유의 종류
     */
    change_type?: PointHistoryType | null;
};

/**
 * RankingResponse
 */
export type RankingResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Total Point
     */
    total_point: number;
};

/**
 * ResponseModel[GetLimitResponse]
 */
export type ResponseModelGetLimitResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: GetLimitResponse;
};

/**
 * ResponseModel[List[User]]
 */
export type ResponseModelListUser = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<User>;
};

/**
 * ResponseModel[User]
 */
export type ResponseModelUser = {
    /**
     * Success
     */
    success: boolean;
    /**
     * 응답 데이터
     */
    data: User;
};

/**
 * ResponseModel[bool]
 */
export type ResponseModelBool = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: boolean;
};

/**
 * ResponseModel[int]
 */
export type ResponseModelInt = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: number;
};

/**
 * ResponseModel[list[PointHistory]]
 */
export type ResponseModelListPointHistory = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<PointHistory>;
};

/**
 * ResponseModel[list[RankingResponse]]
 */
export type ResponseModelListRankingResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Data
     *
     * 응답 데이터
     */
    data: Array<RankingResponse>;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     *
     * 고유 ID. 교사, 서비스의 경우 자동생성. 학생의 경우 학번 사용
     */
    id?: number | null;
    /**
     * 유저 종류 (학생, 교사, 서비스)
     */
    type: UserType;
    /**
     * Name
     *
     * 이름
     */
    name: string;
    /**
     * Grade
     *
     * 학년
     */
    grade: number | null;
    /**
     * Number
     *
     * 반
     */
    number: number | null;
    /**
     * Point
     *
     * 보유 포인트
     */
    point?: number;
    /**
     * Total Point
     *
     * 누적 포인트
     */
    total_point?: number;
    /**
     * Is Admin
     *
     * 관리자 여부
     */
    is_admin?: boolean;
    /**
     * 해당 유저가 포인트 지급/차감시 포인트 기록 타입
     */
    history_type?: PointHistoryType | null;
};

/**
 * UserType
 */
export type UserType = 'student' | 'teacher' | 'service';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LoginAuthLoginPostData = {
    body: LoginForm;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * ID 또는 비밀번호가 일치하지 않습니다.
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * 정상적으로 로그인이 되었음
     */
    200: ResponseModelUser;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * 정상적으로 로그아웃이 되었음
     */
    204: void;
};

export type LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type GetCurrentUserAuthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth';
};

export type GetCurrentUserAuthGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음.
     */
    401: ErrorResponse;
};

export type GetCurrentUserAuthGetError = GetCurrentUserAuthGetErrors[keyof GetCurrentUserAuthGetErrors];

export type GetCurrentUserAuthGetResponses = {
    /**
     * 세션이 정상적으로 유효함
     */
    200: ResponseModelUser;
};

export type GetCurrentUserAuthGetResponse = GetCurrentUserAuthGetResponses[keyof GetCurrentUserAuthGetResponses];

export type ChangePasswordNewAuthPasswordPostData = {
    body: ChangePasswordNewForm;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type ChangePasswordNewAuthPasswordPostErrors = {
    /**
     * 이미 비밀번호가 설정되어있음.
     */
    400: ErrorResponse;
    /**
     * 유저을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordNewAuthPasswordPostError = ChangePasswordNewAuthPasswordPostErrors[keyof ChangePasswordNewAuthPasswordPostErrors];

export type ChangePasswordNewAuthPasswordPostResponses = {
    /**
     * 비밀번호 변경 성공
     */
    204: void;
};

export type ChangePasswordNewAuthPasswordPostResponse = ChangePasswordNewAuthPasswordPostResponses[keyof ChangePasswordNewAuthPasswordPostResponses];

export type ChangePasswordAuthPasswordPutData = {
    body: ChangePasswordForm;
    path?: never;
    query?: never;
    url: '/auth/password';
};

export type ChangePasswordAuthPasswordPutErrors = {
    /**
     * 기존 비밀번호가 일치하지 않음
     */
    400: ErrorResponse;
    /**
     * 세션이 만료되었거나 유효하지 않음.
     */
    401: ErrorResponse;
    /**
     * 초기회 되지 않은 유저.
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordAuthPasswordPutError = ChangePasswordAuthPasswordPutErrors[keyof ChangePasswordAuthPasswordPutErrors];

export type ChangePasswordAuthPasswordPutResponses = {
    /**
     * 비밀번호 변경 성공
     */
    204: void;
};

export type ChangePasswordAuthPasswordPutResponse = ChangePasswordAuthPasswordPutResponses[keyof ChangePasswordAuthPasswordPutResponses];

export type CheckPasswordExistsAuthPasswordExistsUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: {
        /**
         * T
         */
        t?: UserType | null;
    };
    url: '/auth/password/exists/{user_id}';
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetErrors = {
    /**
     * 해당 유저의 타입이 지정된 타입과 일치하지 않음
     */
    400: ErrorResponse;
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetError = CheckPasswordExistsAuthPasswordExistsUserIdGetErrors[keyof CheckPasswordExistsAuthPasswordExistsUserIdGetErrors];

export type CheckPasswordExistsAuthPasswordExistsUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelBool;
};

export type CheckPasswordExistsAuthPasswordExistsUserIdGetResponse = CheckPasswordExistsAuthPasswordExistsUserIdGetResponses[keyof CheckPasswordExistsAuthPasswordExistsUserIdGetResponses];

export type GetLimitPointLimitTargetUserIdGetData = {
    body?: never;
    path: {
        /**
         * Target User Id
         */
        target_user_id: number;
    };
    query?: never;
    url: '/point/limit/{target_user_id}';
};

export type GetLimitPointLimitTargetUserIdGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLimitPointLimitTargetUserIdGetError = GetLimitPointLimitTargetUserIdGetErrors[keyof GetLimitPointLimitTargetUserIdGetErrors];

export type GetLimitPointLimitTargetUserIdGetResponses = {
    /**
     * 정상적으로 처리됨
     */
    200: ResponseModelGetLimitResponse;
};

export type GetLimitPointLimitTargetUserIdGetResponse = GetLimitPointLimitTargetUserIdGetResponses[keyof GetLimitPointLimitTargetUserIdGetResponses];

export type GetLimitSessionPointLimitGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/point/limit';
};

export type GetLimitSessionPointLimitGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
};

export type GetLimitSessionPointLimitGetError = GetLimitSessionPointLimitGetErrors[keyof GetLimitSessionPointLimitGetErrors];

export type GetLimitSessionPointLimitGetResponses = {
    /**
     * 정상적으로 처리됨
     */
    200: ResponseModelInt;
};

export type GetLimitSessionPointLimitGetResponse = GetLimitSessionPointLimitGetResponses[keyof GetLimitSessionPointLimitGetResponses];

export type GrantPointsPointGrantPostData = {
    body: PointOperation;
    path?: never;
    query?: never;
    url: '/point/grant';
};

export type GrantPointsPointGrantPostErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 지급할 학생을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * 주간 포인트 지급 한도를 초과할 경우 발생합니다. 관리자 계정의 경우 한도가 적용되지 않습니다.
     */
    429: ErrorResponse;
};

export type GrantPointsPointGrantPostError = GrantPointsPointGrantPostErrors[keyof GrantPointsPointGrantPostErrors];

export type GrantPointsPointGrantPostResponses = {
    /**
     * 정상적으로 지급이 되었음
     */
    204: void;
};

export type GrantPointsPointGrantPostResponse = GrantPointsPointGrantPostResponses[keyof GrantPointsPointGrantPostResponses];

export type DeductPointsPointDeductPostData = {
    body: PointOperation;
    path?: never;
    query?: never;
    url: '/point/deduct';
};

export type DeductPointsPointDeductPostErrors = {
    /**
     * 포인트 부족
     */
    400: ErrorResponse;
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 차감할 학생을 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeductPointsPointDeductPostError = DeductPointsPointDeductPostErrors[keyof DeductPointsPointDeductPostErrors];

export type DeductPointsPointDeductPostResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelInt;
    /**
     * 정상적으로 차감이 되었음
     */
    204: void;
};

export type DeductPointsPointDeductPostResponse = DeductPointsPointDeductPostResponses[keyof DeductPointsPointDeductPostResponses];

export type PointHistoryPointHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/point/history';
};

export type PointHistoryPointHistoryGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PointHistoryPointHistoryGetError = PointHistoryPointHistoryGetErrors[keyof PointHistoryPointHistoryGetErrors];

export type PointHistoryPointHistoryGetResponses = {
    /**
     * 정상처리
     */
    200: ResponseModelListPointHistory;
};

export type PointHistoryPointHistoryGetResponse = PointHistoryPointHistoryGetResponses[keyof PointHistoryPointHistoryGetResponses];

export type GetStudentRankingPointRankingStudentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/point/ranking/student';
};

export type GetStudentRankingPointRankingStudentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudentRankingPointRankingStudentGetError = GetStudentRankingPointRankingStudentGetErrors[keyof GetStudentRankingPointRankingStudentGetErrors];

export type GetStudentRankingPointRankingStudentGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelListRankingResponse;
};

export type GetStudentRankingPointRankingStudentGetResponse = GetStudentRankingPointRankingStudentGetResponses[keyof GetStudentRankingPointRankingStudentGetResponses];

export type GetTeacherRankingPointRankingTeacherGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/point/ranking/teacher';
};

export type GetTeacherRankingPointRankingTeacherGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTeacherRankingPointRankingTeacherGetError = GetTeacherRankingPointRankingTeacherGetErrors[keyof GetTeacherRankingPointRankingTeacherGetErrors];

export type GetTeacherRankingPointRankingTeacherGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseModelListRankingResponse;
};

export type GetTeacherRankingPointRankingTeacherGetResponse = GetTeacherRankingPointRankingTeacherGetResponses[keyof GetTeacherRankingPointRankingTeacherGetResponses];

export type GetPointBalancePointTargetUserIdGetData = {
    body?: never;
    path: {
        /**
         * Target User Id
         */
        target_user_id: number;
    };
    query?: never;
    url: '/point/{target_user_id}';
};

export type GetPointBalancePointTargetUserIdGetErrors = {
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPointBalancePointTargetUserIdGetError = GetPointBalancePointTargetUserIdGetErrors[keyof GetPointBalancePointTargetUserIdGetErrors];

export type GetPointBalancePointTargetUserIdGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelInt;
};

export type GetPointBalancePointTargetUserIdGetResponse = GetPointBalancePointTargetUserIdGetResponses[keyof GetPointBalancePointTargetUserIdGetResponses];

export type SearchSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * T
         */
        t?: Array<UserType>;
    };
    url: '/search';
};

export type SearchSearchGetErrors = {
    /**
     * 세션이 만료되었거나 유효하지 않음
     */
    401: ErrorResponse;
    /**
     * 권한이 없음
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchSearchGetError = SearchSearchGetErrors[keyof SearchSearchGetErrors];

export type SearchSearchGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelListUser;
};

export type SearchSearchGetResponse = SearchSearchGetResponses[keyof SearchSearchGetResponses];

export type TeacherGetByNameSearchTeacherUserNameGetData = {
    body?: never;
    path: {
        /**
         * User Name
         */
        user_name: string;
    };
    query?: never;
    url: '/search/teacher/{user_name}';
};

export type TeacherGetByNameSearchTeacherUserNameGetErrors = {
    /**
     * 유저를 찾을 수 없음
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeacherGetByNameSearchTeacherUserNameGetError = TeacherGetByNameSearchTeacherUserNameGetErrors[keyof TeacherGetByNameSearchTeacherUserNameGetErrors];

export type TeacherGetByNameSearchTeacherUserNameGetResponses = {
    /**
     * 정상 처리
     */
    200: ResponseModelUser;
};

export type TeacherGetByNameSearchTeacherUserNameGetResponse = TeacherGetByNameSearchTeacherUserNameGetResponses[keyof TeacherGetByNameSearchTeacherUserNameGetResponses];

export type GetStudentsAdminStudentGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * 페이지 번호
         */
        page?: number;
        /**
         * Size
         *
         * 페이지 당 유저 데이터 갯수 (최대 100)
         */
        size?: number;
    };
    url: '/admin/student';
};

export type GetStudentsAdminStudentGetErrors = {
    /**
     * 권한 거부
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStudentsAdminStudentGetError = GetStudentsAdminStudentGetErrors[keyof GetStudentsAdminStudentGetErrors];

export type GetStudentsAdminStudentGetResponses = {
    /**
     * 정상적으로 처리 됨
     */
    200: ResponseModelListUser;
};

export type GetStudentsAdminStudentGetResponse = GetStudentsAdminStudentGetResponses[keyof GetStudentsAdminStudentGetResponses];

export type UpdateStudentsPointAdminPointPostData = {
    body: AdminPointRequest;
    path?: never;
    query?: never;
    url: '/admin/point';
};

export type UpdateStudentsPointAdminPointPostErrors = {
    /**
     * 권한 거부
     */
    403: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateStudentsPointAdminPointPostError = UpdateStudentsPointAdminPointPostErrors[keyof UpdateStudentsPointAdminPointPostErrors];

export type UpdateStudentsPointAdminPointPostResponses = {
    /**
     * 정상 처리
     */
    204: void;
};

export type UpdateStudentsPointAdminPointPostResponse = UpdateStudentsPointAdminPointPostResponses[keyof UpdateStudentsPointAdminPointPostResponses];
